import grammar.stack_slot
import grammar.pending_element
import grammar.hash_builtin
import grammar.ndarray_index
import grammar.type_check
import grammar.promote
import grammar.cond_branch
import grammar.generic_signature_ast
import grammar.generic
import grammar.defer
import grammar.type_name
import grammar.operator_overload
import grammar.list_builtin
import grammar.lazy_runtime
import grammar.json_builtin
import grammar.print_builtin
import grammar.limb_builtin
import grammar.bit_builtin
import grammar.gpu_builtin
import grammar.atomic_builtin
import grammar.gpu_math_builtin
import grammar.gpu_shared_builtin
import grammar.var_builtin
import grammar.identifier
import grammar.int_literal
import compiler.bignum
import grammar.float_literal
import compiler.expression_ast
import grammar.retained_ast
import compiler.statement_ast
import compiler.loop_ast
import compiler.gpu_ast
import compiler.tile_ast
import compiler.global_ast
import compiler.function_record_ast
import compiler.function_ast
import compiler.linkage_ast
import grammar.string_literal
import grammar.template_string
import grammar.primary_expr
import grammar.binary_op
import grammar.postfix_expr
import grammar.unary_expression
import grammar.array_field_init
import grammar.multiplicative_expr
import grammar.additive_expr
import grammar.shift_expr
import grammar.relational_expr
import grammar.equality_expr
import grammar.bitwise_and_expr
import grammar.bitwise_xor_expr
import grammar.bitwise_or_expr
import grammar.logical_and_expr
import grammar.logical_or_expr
import grammar.conditional_expr
import grammar.increment
import grammar.multi_assign
import grammar.expression
import grammar.loop_rotate
import grammar.while_statement
import grammar.typed_identifier
import grammar.variable_declaration
import grammar.for_statement
import grammar.switch_statement
import grammar.goto_statement
import grammar.statement
import grammar.inline_call
import grammar.type_alias_declaration
import grammar.struct_declaration
import grammar.union_declaration
import grammar.enum_declaration
import grammar.import_statement
import grammar.c_import_statement
import grammar.extern_statement
import grammar.generator_decl
import grammar.kernel_decl
import grammar.protobuf_builtin
import grammar.gpu_for
import grammar.asm_function
import grammar.program
# O7: induction-variable pointers (after the grammar it emits through)
import compiler.ivopt
import code_generator.statement_ast
import code_generator.loop_ast
import code_generator.gpu_ast
import code_generator.global_ast
import code_generator.function_ast
import code_generator.linkage_ast
# C3.5: the optional optimizer pass, between a header's parse and its walk
import compiler.ast_opt
import grammar.ast_statement
import grammar.ast_declaration
import grammar.ast_loop
import grammar.ast_gpu
import compiler.tile_analysis
import compiler.tile_plan
import code_generator.tile_ptx
import code_generator.tile_host
import grammar.ast_tile
import grammar.ast_global
import grammar.ast_function
import grammar.ast_linkage
import code_generator.expression_ast
import grammar.ast_expression
import grammar.defer_ast

# no idea why this is necessary:
int grammar_no_reason_temp_var

import grammar.ast_function_record
import code_generator.function_record_ast
