import grammar.hash_builtin
import grammar.promote
import grammar.generic
import grammar.defer
import grammar.type_name
import grammar.list_builtin
import grammar.json_builtin
import grammar.print_builtin
import grammar.var_builtin
import grammar.identifier
import grammar.int_literal
import compiler.bignum
import grammar.float_literal
import grammar.string_literal
import grammar.template_string
import grammar.primary_expr
import grammar.binary_op
import grammar.postfix_expr
import grammar.unary_expression
import grammar.array_field_init
import grammar.multiplicative_expr
import grammar.additive_expr
import grammar.shift_expr
import grammar.relational_expr
import grammar.equality_expr
import grammar.bitwise_and_expr
import grammar.bitwise_xor_expr
import grammar.bitwise_or_expr
import grammar.logical_and_expr
import grammar.logical_or_expr
import grammar.conditional_expr
import grammar.expression
import grammar.while_statement
import grammar.typed_identifier
import grammar.variable_declaration
import grammar.for_statement
import grammar.switch_statement
import grammar.statement
import grammar.type_alias_declaration
import grammar.struct_declaration
import grammar.union_declaration
import grammar.enum_declaration
import grammar.import_statement
import grammar.c_import_statement
import grammar.extern_statement
import grammar.generator_decl
import grammar.program

# no idea why this is necessary:
int grammar_no_reason_temp_var
