/*
Shared x86/x64 randomized round-trip driver for the assembler/
disassembler property/fuzz tests (docs/projects/assembler_disassembler.md,
issue #171). tests/asm_fuzz_x86_test.w and tests/asm_fuzz_x64_test.w both
call asm_fuzz_x86_run with their arch's corpus file, arch id, decode mode
(4/8) and GP register count (8/16) — the x86 and x64 modes share one
decoder/encoder/parser/formatter family (libs/asm/x86_decode.w,
x86_encode.w, text.w, format.w), so one driver covers both.

Instruction generation reuses the existing corpus-enumeration machinery
(asm_corpus_load, the same tests/asm/corpus_*.txt fixtures the hand-written
asm_x86_asm_test/asm_x64_test corpus tests already parse) instead of a
separate generator: each iteration samples one corpus line at random (a
concrete instruction of some "form" the compiler is known to emit),
parses it into a structured asm_insn, then randomizes its concrete
register/immediate/displacement payload within the value's legal range
for its operand kind and size. This means adding a new instruction form
to tests/asm/corpus_*.txt (the existing, documented way to grow coverage,
see "Maintaining the runtime stubs" / corpus-growth notes in
docs/projects/assembler_disassembler.md) is automatically picked up by
every future fuzz run — there is no separate form table to remember to
update.

Two properties are checked per generated instruction, matching the
issue's wording literally:

  - decode(encode(insn)) == insn: encode the mutated insn, decode the
    result, re-encode that, and require the two encodings' bytes to
    match — the byte-identity idiom asm_x86_asm_test's
    test_wv2_encode_identity already uses, not a struct/format comparison
    of insn against the decoded-back instruction (insn has no equality
    operator, and a few forms — e.g. shl/sar/shr's by-cl form, whose
    count register is architecturally fixed and has no ModRM encoding —
    legitimately can't reproduce every mutated field, only what they
    actually encode; byte-identity of the two encodes tolerates that,
    since both agree on what the encoder never looked at).
  - parse(format(insn)) == insn: format the mutated insn to text, parse
    it back, and require a second format of the reparsed instruction to
    reproduce the same text (canonical text is the equality proxy here,
    mirroring asm_x86_asm_test's test_corpus_semantic_roundtrip, but on
    randomized operands instead of the fixed corpus text).

Register/immediate/displacement mutation never has to respect hardware
validity (e.g. esp cannot be a SIB index) because both properties are
pure round-trip/idempotence checks of this library's own functions, not
assertions that the generated bytes are a real, executable instruction:
encode/decode/format/parse are total deterministic functions of the
struct fields they're given, so decode(encode(x)) and parse(format(x))
are exercised faithfully however the fields were chosen. What must be
bounded is only what would otherwise index out of range (register
numbers beyond the arch's count) or defeat the "same form" premise
(operand *kind* is left untouched; only the concrete payload varies).

Compiled by bin/wv2 only (not part of the seed graph).
*/
import lib.lib
import lib.assert
import libs.asm.insn
import libs.asm.hexutil
import libs.asm.x86_decode
import libs.asm.x86_encode
import libs.asm.text
import libs.asm.format
import tests.asm_fuzz_prng


# Corpus entries whose text is a ' ; '-joined multi-instruction sequence
# describe more than one instruction; skip them (the corpus tests already
# cover sequences via the whole-.text sweep, and a single asm_x86_parse
# call only ever reads the first instruction of such a line).
int asm_fuzz_has_sequence(char* text):
	int i = 0
	while (text[i] != 0):
		if (text[i] == ' ' && text[i + 1] == ';' && text[i + 2] == ' '):
			return 1
		i = i + 1
	return 1 == 2


int asm_fuzz_bytes_equal(char* a, int an, char* b, int bn):
	if (an != bn):
		return 1 == 2
	int i = 0
	while (i < an):
		if ((a[i] & 255) != (b[i] & 255)):
			return 1 == 2
		i = i + 1
	return 1


# Re-pick a scale factor from the legal SIB set {1,2,4,8}.
int asm_fuzz_pick_scale():
	int s = fuzz_range(4)
	if (s == 0):
		return 1
	if (s == 1):
		return 2
	if (s == 2):
		return 4
	return 8


# The byte width a reg/mem operand pins the instruction to, or -1 if op
# isn't a sized reg/mem operand at all (imm/label operands carry no width
# of their own here).
int asm_fuzz_operand_pin_size(asm_operand* op):
	if (op.kind == ASM_OP_REG() | op.kind == ASM_OP_MEM()):
		return op.size
	return -1


# The real encoded width of an immediate operand is usually pinned by a
# *different* operand of the same instruction (mov cl,0x10's immediate is
# byte-wide because cl is, not because the immediate operand's own .size
# was ever set — the text parser only stamps size_hint onto an operand a
# size keyword directly precedes). Scanning every operand for a sized
# reg/mem operand, and otherwise falling back to the immediate's own
# .size (set when a size keyword *does* precede it, e.g. "push dword
# 0x12", or when it's the sole operand of a form whose corpus text always
# carries one, e.g. plain "push 0x10"), reproduces what the encoder will
# actually use. Getting this wrong previously showed up immediately as a
# fuzz failure: a random 32-bit value assigned to a byte-immediate slot
# gets truncated by the encoder, so decode(encode(insn)) != insn.
# Sentinel width meaning "no operand anywhere gave a real width": e.g.
# "int 0x80", a single implicit-imm8 operand with no size keyword and no
# reg/mem to pin it.
int ASM_FUZZ_WIDTH_UNKNOWN():
	return 0 - 1


int asm_fuzz_insn_width(asm_insn* insn, asm_operand* target):
	int s = asm_fuzz_operand_pin_size(&insn.op1)
	if (s > 0):
		return s
	s = asm_fuzz_operand_pin_size(&insn.op2)
	if (s > 0):
		return s
	s = asm_fuzz_operand_pin_size(&insn.op3)
	if (s > 0):
		return s
	if (target.size > 0):
		return target.size
	return ASM_FUZZ_WIDTH_UNKNOWN()


# Randomize one operand's concrete payload in place, leaving its kind
# (and, for mem, which of base/index/disp are present) untouched. Label
# operands (branch/call targets, which parse as ASM_OP_LABEL — see
# libs/asm/text.w) are deliberately left alone: they carry a symbolic
# ".+N" displacement whose legal range depends on the specific branch
# form, which is exactly the kind of per-mnemonic knowledge this driver
# avoids needing.
void asm_fuzz_mutate_operand(asm_insn* insn, asm_operand* op, int reg_limit):
	if (op.kind == ASM_OP_REG()):
		if (op.rclass == ASM_RCLASS_GP()):
			op.reg = fuzz_range(reg_limit)
		return
	if (op.kind == ASM_OP_IMM()):
		int width = asm_fuzz_insn_width(insn, op)
		if (width == ASM_FUZZ_WIDTH_UNKNOWN() | width == 1):
			# Byte immediates are not uniformly sign-extended by this
			# decoder: e.g. "int 0x80"'s vector number and "mov cl,imm8"
			# both read the byte unsigned (0x80 stays 0x80; a mutated value
			# with the top bit set came back positive, not "-0x..", which
			# looked like a round-trip bug until this was traced to the
			# decoder's own convention for these forms). 0..127 is
			# bit-identical whichever convention a given form uses, so it
			# sidesteps needing a per-mnemonic signedness table.
			op.imm = fuzz_range(128)
		else if (width == 8):
			# movabs r64, imm64: imm carries the low 32 bits, imm_hi the high.
			op.imm = fuzz_next()
			op.imm_hi = fuzz_next()
		else if (width == 2):
			int v = fuzz_next() & 65535
			if (v >= 32768):
				v = v - 65536
			op.imm = v
		else:
			op.imm = fuzz_next()
		return
	if (op.kind == ASM_OP_MEM()):
		if (op.base == ASM_BASE_RIP()):
			# x64 [rip+disp32]: keep the sentinel, only the displacement varies.
			op.disp = fuzz_next()
			return
		if (op.base >= 0):
			op.base = fuzz_range(reg_limit)
		if (op.index >= 0):
			op.index = fuzz_range(reg_limit)
			op.scale = asm_fuzz_pick_scale()
		op.disp = fuzz_next()


void asm_fuzz_mutate_insn(asm_insn* insn, int reg_limit):
	asm_fuzz_mutate_operand(insn, &insn.op1, reg_limit)
	asm_fuzz_mutate_operand(insn, &insn.op2, reg_limit)
	asm_fuzz_mutate_operand(insn, &insn.op3, reg_limit)


void asm_fuzz_report_bytes(char* what, int seed, int iter, int line, char* text, char* want, int want_n, char* got, int got_n):
	print2(c"asm fuzz mismatch (")
	print2(what)
	print2(c") seed=")
	print2(itoa(seed))
	print2(c" iter=")
	print2(itoa(iter))
	print2(c" corpus_line=")
	println2(itoa(line))
	print2(c"  form: ")
	println2(text)
	print2(c"  want: ")
	println2(asm_hex_encode(want, want_n))
	print2(c"  got:  ")
	println2(asm_hex_encode(got, got_n))


void asm_fuzz_report_text(char* what, int seed, int iter, int line, char* text, char* want, char* got):
	print2(c"asm fuzz mismatch (")
	print2(what)
	print2(c") seed=")
	print2(itoa(seed))
	print2(c" iter=")
	print2(itoa(iter))
	print2(c" corpus_line=")
	println2(itoa(line))
	print2(c"  form: ")
	println2(text)
	print2(c"  want: ")
	println2(want)
	print2(c"  got:  ")
	println2(got)


# Randomized round-trip fuzzing over one arch's corpus. corpus_path is the
# tests/asm/corpus_*.txt fixture, arch is ASM_ARCH_X86()/ASM_ARCH_X64()
# (what asm_x86_parse/insn.arch expect), mode is the decoder's 32/64-bit
# selector (4 or 8, matching asm_x86_decode's existing 'mode' parameter),
# reg_limit is the GP register count (8 or 16) and label names the arch in
# progress/failure messages.
void asm_fuzz_x86_run(char* corpus_path, int arch, int mode, int reg_limit, char* label):
	list[asm_corpus_entry] entries = asm_corpus_load(corpus_path)
	asserts(c"empty corpus", entries.length > 50)
	int seed = ASM_FUZZ_SEED()
	fuzz_seed(seed)
	int iterations = asm_fuzz_iterations()
	int checked = 0
	int skipped = 0
	int i = 0
	while (i < iterations):
		int idx = fuzz_range(entries.length)
		asm_corpus_entry entry = entries[idx]
		if (asm_fuzz_has_sequence(entry.text)):
			skipped = skipped + 1
			i = i + 1
			continue
		asm_insn insn
		int ok = asm_x86_parse(entry.text, arch, &insn)
		if (ok == 0):
			skipped = skipped + 1
			i = i + 1
			continue
		asm_fuzz_mutate_insn(&insn, reg_limit)

		# Property 1: decode(encode(insn)) == insn. Byte-identity of
		# encode -> decode -> encode is the equality check (not a
		# format-text comparison of insn vs. the decoded insn): a few
		# forms have operand bits the encoding genuinely can't represent
		# (e.g. shl/sar/shr's by-cl form has no ModRM field for *which*
		# register holds the count — it's architecturally always cl, so
		# encode ignores whatever register the mutator put there). That
		# makes the encoder legitimately "forget" such a field, which
		# byte-identity tolerates (both encodes agree, since encode never
		# looked at the mutated field) but a struct/format comparison of
		# insn against the decoded-back insn would not — matching the
		# byte-only "encode identity" idiom asm_x86_asm_test's
		# test_wv2_encode_identity already uses for the same reason.
		asm_buffer* b1 = asm_buffer_new()
		asm_x86_encode(b1, &insn)
		asm_insn insn2
		asm_x86_decode(b1.data, b1.length, 0, mode, &insn2)
		asm_buffer* b2 = asm_buffer_new()
		asm_x86_encode(b2, &insn2)
		if (asm_fuzz_bytes_equal(b1.data, b1.length, b2.data, b2.length) == 0):
			asm_fuzz_report_bytes(label, seed, i, entry.line, entry.text, b1.data, b1.length, b2.data, b2.length)
			exit(1)
		asm_buffer_free(b1)
		asm_buffer_free(b2)

		# Property 2: parse(format(insn)) == insn.
		char* f1 = asm_format(&insn)
		asm_insn insn3
		asm_x86_parse(f1, arch, &insn3)
		char* f3 = asm_format(&insn3)
		if (strcmp(f1, f3) != 0):
			asm_fuzz_report_text(label, seed, i, entry.line, entry.text, f1, f3)
			exit(1)

		checked = checked + 1
		i = i + 1
	print2(label)
	print2(c" fuzz: seed=")
	print2(itoa(seed))
	print2(c" iterations=")
	print2(itoa(iterations))
	print2(c" checked=")
	print2(itoa(checked))
	print2(c" skipped_sequences=")
	println2(itoa(skipped))
