# wbuild: x64
import lib.testing
import tools.ast_audit


void test_ast_audit_selects_only_direct_compilations():
	json_value* root = json_parse(c"{\"dirs\":[\"bin\"],\"targets\":[{\"name\":\"sample\",\"steps\":[{\"cmd\":[\"bin/wv2\",\"x64\",\"program.w\",\"-o\",\"out\"],\"stdin\":\"keep\",\"env\":[\"K=V\"]},{\"cmd\":[\"bin/wv2\",\"check\",\"--json\",\"--lint\",\"program.w\"]},{\"cmd\":[\"./w\",\"w.w\",\"-o\",\"bin/wv2\"]},{\"cmd\":[\"bin/wv2\",\"--ast-required\",\"w.w\"]},{\"cmd\":[\"bin/wv2\",\"symbols\",\"--json\",\"w.w\"]},{\"cmd\":[\"sh\",\"-c\",\"bin/wv2 program.w\"]},{\"cmd\":[\"bin/wv2_fake\",\"w.w\"]},{\"cmd\":[\"bin/wv2\",\"-o\",\"output.w\"]},{\"cmd\":[\"bin/wv2_64\",\"--import-root\",\"directory.w\",\"--help\"]},{\"cmd\":[\"bin/wv3\",\"--strict\",\"w.w\",\"-o\",\"bin/wv4\"]}]}]}")
	json_value* report = ast_audit_manifest(root)
	assert1(report != 0)
	assert_equal(3, jfield_int(report, c"changed_steps", -1))
	assert_equal(1, jfield_int(report, c"explicit_ast_steps", -1))
	assert_equal(3, jfield_int(report, c"query_or_sourceless_steps", -1))
	assert_equal(3, jfield_int(report, c"other_steps", -1))
	json_value* target = json_array_get(jfield_array(root, c"targets"), 0)
	json_value* steps = jfield_array(target, c"steps")
	json_value* first = json_array_get(steps, 0)
	assert_strings_equal(c"keep", jfield_string(first, c"stdin"))
	json_value* cmd = jfield_array(first, c"cmd")
	assert_equal(6, json_array_length(cmd))
	assert_strings_equal(c"out", json_array_get(cmd, 4).string_value)
	assert_strings_equal(c"--ast-full-expressions", json_array_get(cmd, 5).string_value)
	first = json_array_get(steps, 1)
	cmd = jfield_array(first, c"cmd")
	assert_strings_equal(c"--json", json_array_get(cmd, 2).string_value)
	assert_strings_equal(c"--ast-full-expressions", json_array_get(cmd, 5).string_value)
	first = json_array_get(steps, 2)
	assert_equal(4, json_array_length(jfield_array(first, c"cmd")))
	json_value* repeated = ast_audit_manifest(root)
	assert_equal(0, jfield_int(repeated, c"changed_steps", -1))
	assert_equal(4, jfield_int(repeated, c"explicit_ast_steps", -1))
	json_free(repeated)
	json_free(report)
	json_free(root)


void test_ast_audit_census_is_sorted_and_preserves_missing_stats():
	char* input = c"compiling 'w.w'\n{\"ast_fallback\":true,\"file\":\"z.w\",\"line\":2,\"column\":1,\"token\":\"new\"}\n{\"ast_fallback\":true,\"file\":\"a.w\",\"line\":3,\"column\":4,\"token\":\"(\"}\n{\"ast_fallback\":true,\"file\":\"z.w\",\"line\":4,\"column\":5,\"token\":\"new\"}\nAST expression roots: 20\nStreaming expression roots: 3\nAST expression roots: 7\nStreaming return statements: 0"
	json_value* report = ast_audit_census(input)
	assert_equal(3, jfield_int(report, c"fallback_records", -1))
	assert_equal(0, jfield_int(report, c"invalid_records", -1))
	assert_equal(1, jfield_int(report, c"ignored_lines", -1))
	assert_equal(1, jfield_flag(report, c"records_match_streaming_roots"))
	json_value* files = jfield_array(report, c"by_file")
	assert_equal(2, json_array_length(files))
	json_value* row = json_array_get(files, 0)
	assert_strings_equal(c"a.w", jfield_string(row, c"file"))
	assert_equal(1, jfield_int(row, c"count", -1))
	row = json_array_get(files, 1)
	assert_strings_equal(c"z.w", jfield_string(row, c"file"))
	assert_equal(2, jfield_int(row, c"count", -1))
	json_value* tokens = jfield_array(report, c"by_token")
	row = json_array_get(tokens, 0)
	assert_strings_equal(c"(", jfield_string(row, c"token"))
	row = json_array_get(tokens, 1)
	assert_equal(2, jfield_int(row, c"count", -1))
	json_value* counters = jfield_array(report, c"counters")
	row = json_array_get(counters, 0)
	assert_strings_equal(c"AST expression roots", jfield_string(row, c"counter"))
	assert_equal(27, jfield_int(row, c"count", -1))
	json_free(report)
	report = ast_audit_census(c"")
	assert_equal(0, json_array_length(jfield_array(report, c"counters")))
	assert_equal(0, jfield_int(report, c"fallback_records", -1))
	assert_equal(json_type_null(), json_object_get(report, c"records_match_streaming_roots").type)
	json_free(report)


void test_ast_audit_reports_malformed_records():
	json_value* report = ast_audit_census(c"{\"ast_fallback\": true\n{\"ast_fallback\":true,\"file\":\"a.w\",\"token\":\"x\"}\nAST expression roots: nope\n{\"unrelated\":true}\n{\"ast_fallback\":\"true\",\"file\":\"a.w\",\"line\":1,\"column\":1,\"token\":\"x\"}\n{\"ast_fallback\":null}\n")
	assert_equal(5, jfield_int(report, c"invalid_records", -1))
	assert_equal(1, jfield_int(report, c"ignored_lines", -1))
	assert_equal(0, jfield_int(report, c"fallback_records", -1))
	json_free(report)


void test_ast_audit_command_option_operands():
	json_value* tree_query = json_parse(c"[\"bin/wv2\",\"tree\",\"--json\",\"program.w\"]")
	assert_equal(3, ast_audit_command_kind(tree_query))
	json_free(tree_query)
	json_value* cmd = json_parse(c"[\"bin/wv2\",\"-v\",\"program.w\"]")
	assert_equal(1, ast_audit_command_kind(cmd))
	json_free(cmd)
	cmd = json_parse(c"[\"bin/wv2\",\"--import-root=directory.w\",\"--ptx=trace.w\"]")
	assert_equal(3, ast_audit_command_kind(cmd))
	json_free(cmd)
	cmd = json_parse(c"[\"bin/wv2\",\"--import-root\",\"--ast-required\",\"program.w\",\"-o\",\"--ast-audit\"]")
	assert_equal(1, ast_audit_command_kind(cmd))
	json_free(cmd)


void test_ast_audit_records_and_counters_consistency():
	json_value* report = ast_audit_census(c"Streaming expression roots: 0\nAST if headers: 4\nStreaming if headers: 0\nAST while headers: 2\nStreaming while headers: 0\n")
	assert_equal(0, jfield_int(report, c"invalid_records", -1))
	assert_equal(1, jfield_flag(report, c"records_match_streaming_roots"))
	json_free(report)
	report = ast_audit_census(c"Streaming expression roots: 1\n")
	json_value* matching = json_object_get(report, c"records_match_streaming_roots")
	assert_equal(json_type_bool(), matching.type)
	assert_equal(0, matching.int_value)
	json_free(report)
	report = ast_audit_census(c"{\"ast_fallback\":true,\"file\":\"a.w\",\"line\":1,\"column\":1,\"token\":\"x\"}\r\nStreaming expression roots: 1\r\n{\"ast_fallback\":true,\"file\":\"b.w\",\"line\":1,\"column\":1,\"token\":\"y\"}\nStreaming expression roots: 1\n")
	assert_equal(2, jfield_int(report, c"fallback_records", -1))
	assert_equal(1, jfield_flag(report, c"records_match_streaming_roots"))
	assert_equal(0, jfield_int(report, c"invalid_records", -1))
	json_free(report)
	report = ast_audit_census(c"Streaming expression roots: 0\nStreaming expression roots: invalid\nAST expression roots\nAST unknown counter: 1\nAST expressions: -1\n")
	assert_equal(4, jfield_int(report, c"invalid_counters", -1))
	assert_equal(4, jfield_int(report, c"invalid_records", -1))
	assert_equal(json_type_null(), json_object_get(report, c"records_match_streaming_roots").type)
	json_free(report)


void test_ast_audit_counters_reject_overflow():
	string_builder* limit = string_new()
	string_append_int(limit, json_int_max())
	assert_equal(json_int_max(), ast_audit_counter_sum(limit.data, 0))
	assert_equal(-1, ast_audit_counter_sum(limit.data, 1))
	assert_equal(-1, ast_audit_counter_sum(c"", 0))
	assert_equal(-1, ast_audit_counter_sum(c"12x", 0))
	assert_equal(-1, ast_audit_counter_sum(c"-1", 0))
	string_builder* input = string_new()
	string_append(input, c"Streaming expression roots: ")
	string_append(input, limit.data)
	string_append(input, c"\nStreaming expression roots: 1\nAST expressions: ")
	string_append(input, limit.data)
	string_append(input, c"0\n")
	json_value* report = ast_audit_census(input.data)
	assert_equal(2, jfield_int(report, c"invalid_counters", -1))
	assert_equal(json_type_null(), json_object_get(report, c"records_match_streaming_roots").type)
	json_free(report)
	string_free(input)
	string_free(limit)


void test_ast_audit_required_manifest_and_fixture_groups():
	json_value* root = json_parse(c"{\"targets\":[{\"name\":\"sample\",\"steps\":[{\"cmd\":[\"env\",\"-u\",\"NO_COLOR\",\"K=V\",\"./bin/wv2\",\"check\",\"--json\",\"program.w\"]},{\"cmd\":[\"/usr/bin/env\",\"--ignore-environment\",\"--unset=X\",\"--\",\"bin/wv3\",\"program.w\"],\"expect_fail\":true},{\"cmd\":[\"bin/wv2\",\"program.w\"],\"expect_status\":2},{\"cmd\":[\"bin/wv2\",\"--ast-expressions\",\"program.w\"]},{\"cmd\":[\"env\",\"K=V\",\"bin/wv2\",\"symbols\",\"program.w\"]},{\"cmd\":[\"bin/wv2\",\"-o\",\"output.w\"]},{\"cmd\":[\"env\",\"--unsupported\",\"bin/wv2\",\"program.w\"]},{\"cmd\":[\"./w\",\"program.w\"]},{\"cmd\":[\"bin/wfixture\",\"bin/wv2\",\"positive.w\",\"negative.w\"]},{\"cmd\":[\"env\",\"K=V\",\"./bin/wfixture\",\"bin/wv2_64\",\"--arch\",\"x64\",\"fixture.w\"]},{\"cmd\":[\"bin/wfixture\",\"--ast-expressions\",\"bin/wv2\",\"fixture.w\"]},{\"cmd\":[\"bin/wfixture\",\"./w\",\"fixture.w\"]},{\"cmd\":[\"env\",\"-u\",\"X\"]}]}]}")
	json_value* report = ast_audit_manifest_mode(root, 1)
	assert_equal(5, jfield_int(report, c"changed_steps", -1))
	assert_equal(1, jfield_int(report, c"required_steps", -1))
	assert_equal(2, jfield_int(report, c"expected_failure_steps", -1))
	assert_equal(2, jfield_int(report, c"fixture_groups", -1))
	json_value* target = json_array_get(jfield_array(root, c"targets"), 0)
	json_value* steps = jfield_array(target, c"steps")
	json_value* cmd = jfield_array(json_array_get(steps, 0), c"cmd")
	assert_strings_equal(c"--ast-required", ast_audit_arg(cmd, 8))
	assert_strings_equal(c"--json", ast_audit_arg(cmd, 6))
	cmd = jfield_array(json_array_get(steps, 1), c"cmd")
	assert_strings_equal(c"--ast-full-expressions", ast_audit_arg(cmd, 6))
	cmd = jfield_array(json_array_get(steps, 2), c"cmd")
	assert_strings_equal(c"--ast-full-expressions", ast_audit_arg(cmd, 2))
	cmd = jfield_array(json_array_get(steps, 8), c"cmd")
	assert_strings_equal(c"--ast-expressions", ast_audit_arg(cmd, 1))
	assert_strings_equal(c"bin/wv2", ast_audit_arg(cmd, 2))
	assert_strings_equal(c"negative.w", ast_audit_arg(cmd, 4))
	cmd = jfield_array(json_array_get(steps, 9), c"cmd")
	assert_strings_equal(c"--ast-expressions", ast_audit_arg(cmd, 3))
	assert_strings_equal(c"x64", ast_audit_arg(cmd, 6))
	json_value* repeated = ast_audit_manifest_mode(root, 1)
	assert_equal(0, jfield_int(repeated, c"changed_steps", -1))
	assert_equal(0, jfield_int(repeated, c"fixture_groups", -1))
	json_free(repeated)
	json_free(report)
	json_free(root)


void test_ast_audit_census_recognizes_statement_and_declaration_stats():
	json_value* report = ast_audit_census(c"AST if regions: 2\nAST while loops: 3\nAST functions: 4\nAST GPU launches: 0\nAST constant expressions: 5\nStreaming expression roots: 0\n")
	assert_equal(0, jfield_int(report, c"invalid_records", -1))
	assert_equal(6, json_array_length(jfield_array(report, c"counters")))
	assert1(jfield_flag(report, c"records_match_streaming_roots"))
	json_free(report)


# The ast_canary_test / ast_canary_64_test steps (tests/ast_canary_test.w)
# already select required mode, so the required suite must leave them alone.
void test_ast_audit_required_manifest_keeps_canary_steps():
	json_value* root = json_parse(c"{\"targets\":[{\"name\":\"ast_canary_test\",\"steps\":[{\"cmd\":[\"bin/wv2\",\"check\",\"--quiet\",\"--ast-retain\",\"--ast-required\",\"w.w\"]}]},{\"name\":\"ast_canary_64_test\",\"steps\":[{\"cmd\":[\"bin/wv2_64\",\"x64\",\"check\",\"--quiet\",\"--ast-retain\",\"--ast-required\",\"w.w\"]}]}]}")
	json_value* report = ast_audit_manifest_mode(root, 1)
	assert_equal(0, jfield_int(report, c"changed_steps", -1))
	assert_equal(2, jfield_int(report, c"explicit_ast_steps", -1))
	json_value* target = json_array_get(jfield_array(root, c"targets"), 1)
	json_value* cmd = jfield_array(json_array_get(jfield_array(target, c"steps"), 0), c"cmd")
	assert_equal(7, json_array_length(cmd))
	assert_strings_equal(c"w.w", ast_audit_arg(cmd, 6))
	json_free(report)
	json_free(root)
