# wbuild: x64
import repl.shell_plan
import lib.assert

shell_plan* checked_plan(char* line):
	shell_plan* p = shell_plan_parse(line)
	asserts(line, p.error == 0)
	asserts(line, p.unsupported == 0)
	return p

void malformed_plan(char* line):
	shell_plan* p = shell_plan_parse(line)
	asserts(line, p.error == 1)
	asserts(line, p.unsupported == 0)
	shell_plan_free(p)

void unsupported_plan(char* line):
	shell_plan* p = shell_plan_parse(line)
	asserts(line, p.unsupported == 1)
	shell_plan_free(p)

void plan_syntax_test():
	shell_plan* p = checked_plan(c" \t\n\n")
	assert_equal(0, p.pipelines.length)
	shell_plan_free(p)
	p = checked_plan(c"a | b && c || d | e && f; g;\n\n")
	assert_equal(5, p.pipelines.length)
	assert_equal(2, p.pipelines[0].commands.length)
	assert_equal(2, p.pipelines[2].commands.length)
	assert_equal(0, p.pipelines[0].condition)
	assert_equal(1, p.pipelines[1].condition)
	assert_equal(2, p.pipelines[2].condition)
	assert_equal(1, p.pipelines[3].condition)
	assert_equal(0, p.pipelines[4].condition)
	assert_strings_equal(c"b", p.pipelines[0].commands[1].text)
	assert_strings_equal(c"e", p.pipelines[2].commands[1].text)
	shell_plan_free(p)
	p = checked_plan(c"\na\nb |\n\nc &&\nd ||\ne\n")
	assert_equal(4, p.pipelines.length)
	assert_equal(2, p.pipelines[1].commands.length)
	assert_equal(1, p.pipelines[2].condition)
	assert_equal(2, p.pipelines[3].condition)
	shell_plan_free(p)
	p = checked_plan(c"echo \\\nword \\\n| cat")
	assert_equal(2, p.pipelines[0].commands.length)
	shell_plan_free(p)

void plan_quotes_test():
	char* raw = c"echo\t 'a|b && c; < > 2>&1 $(x) `x`'  \"a||b; < >\" \\| \\& \\; \\< \\>"
	shell_plan* p = checked_plan(raw)
	assert_equal(1, p.pipelines.length)
	assert_equal(1, p.pipelines[0].commands.length)
	assert_strings_equal(raw, p.pipelines[0].commands[0].text)
	shell_plan_free(p)
	p = checked_plan(c"echo \"a\nb\" 'c\nd' foo\\ bar $HOME *.w [ab] ? ~")
	assert_equal(1, p.pipelines.length)
	shell_plan_free(p)
	p = checked_plan(c"echo \"\\$(literal)\" \\(x\\)")
	shell_plan_free(p)
	p = checked_plan(c"echo foo2>out 2 >other \\2>third '2'>fourth")
	shell_command* c = p.pipelines[0].commands[0]
	assert_strings_equal(c"echo foo2 2 \\2 '2'", c.text)
	assert_equal(4, c.redirects.length)
	for r in c.redirects: assert_equal(1, r.fd)
	shell_plan_free(p)

void plan_redirect_test():
	shell_plan* p = checked_plan(c"\t<in cat\targ 2>err >>out 2>>log 2>&1 1>&2 >'a b' tail")
	shell_command* c = p.pipelines[0].commands[0]
	assert_strings_equal(c"cat\targ tail", c.text)
	assert_equal(7, c.redirects.length)
	assert_equal(0, c.redirects[0].fd)
	assert_equal(0, c.redirects[0].mode)
	assert_strings_equal(c"in", c.redirects[0].path)
	assert_equal(2, c.redirects[1].fd)
	assert_equal(1, c.redirects[1].mode)
	assert_strings_equal(c"err", c.redirects[1].path)
	assert_equal(1, c.redirects[2].fd)
	assert_equal(2, c.redirects[2].mode)
	assert_equal(2, c.redirects[3].fd)
	assert_equal(2, c.redirects[3].mode)
	assert_equal(3, c.redirects[4].mode)
	assert_equal(2, c.redirects[4].fd)
	assert_equal(1, c.redirects[4].source_fd)
	assert1(c.redirects[4].path == 0)
	assert_equal(3, c.redirects[5].mode)
	assert_equal(1, c.redirects[5].fd)
	assert_equal(2, c.redirects[5].source_fd)
	assert_strings_equal(c"a b", c.redirects[6].path)
	shell_plan_free(p)
	p = checked_plan(c"echo >a\\ b >pre' mid'\" end\" >'$(literal)*' >\"\\$HOME\\`\\\\\\\"\\q\" >''")
	c = p.pipelines[0].commands[0]
	assert_strings_equal(c"a b", c.redirects[0].path)
	assert_strings_equal(c"pre mid end", c.redirects[1].path)
	assert_strings_equal(c"$(literal)*", c.redirects[2].path)
	assert_strings_equal(c"$HOME`\\\"\\q", c.redirects[3].path)
	assert_strings_equal(c"", c.redirects[4].path)
	shell_plan_free(p)
	p = checked_plan(c">out 2>&1; echo 2>&1 >out")
	assert_strings_equal(c"", p.pipelines[0].commands[0].text)
	assert_equal(1, p.pipelines[0].commands[0].redirects[0].mode)
	assert_equal(3, p.pipelines[1].commands[0].redirects[0].mode)
	shell_plan_free(p)

void plan_adjacent_redirect_test():
	shell_plan* continued = checked_plan(c"echo 2\\\n>err")
	assert_strings_equal(c"echo", continued.pipelines[0].commands[0].text)
	assert_equal(2, continued.pipelines[0].commands[0].redirects[0].fd)
	shell_plan_free(continued)
	shell_plan* p = checked_plan(c"echo 2>&1>1>>2 1>&2>3")
	shell_command* c = p.pipelines[0].commands[0]
	assert_equal(5, c.redirects.length)
	assert_equal(3, c.redirects[0].mode)
	assert_strings_equal(c"1", c.redirects[1].path)
	assert_strings_equal(c"2", c.redirects[2].path)
	assert_equal(2, c.redirects[2].mode)
	assert_equal(3, c.redirects[3].mode)
	assert_strings_equal(c"3", c.redirects[4].path)
	shell_plan_free(p)

void plan_failures_test():
	unsupported_plan(c"VALUE=one; echo $VALUE")
	unsupported_plan(c"exit 7; echo unreachable")
	unsupported_plan(c"false; echo $?")
	unsupported_plan(c"umask 077; touch file")
	malformed_plan(c"|")
	malformed_plan(c"; echo")
	malformed_plan(c"a |")
	malformed_plan(c"a &&\n")
	malformed_plan(c"a ||")
	malformed_plan(c"a | | b")
	malformed_plan(c"a && ; b")
	malformed_plan(c"a ; ; b")
	malformed_plan(c"a >")
	malformed_plan(c"a > | b")
	malformed_plan(c"a <\nb")
	malformed_plan(c"a 2>&")
	malformed_plan(c"a >>>out")
	malformed_plan(c"echo 'unfinished")
	malformed_plan(c"echo \"unfinished")
	malformed_plan(c"echo trailing\\")
	unsupported_plan(c"a & b")
	unsupported_plan(c"a <<EOF\nhello\nEOF")
	unsupported_plan(c"a <<<word")
	unsupported_plan(c"a |& b")
	unsupported_plan(c"a &>file")
	unsupported_plan(c"a >|file")
	unsupported_plan(c"a <>file")
	unsupported_plan(c"a 3>file")
	unsupported_plan(c"a 12>file")
	unsupported_plan(c"a 2>&3")
	unsupported_plan(c"a 1>&-")
	unsupported_plan(c"a <&0")
	unsupported_plan(c"(a; b)")
	unsupported_plan(c"{ a; b; }")
	unsupported_plan(c"echo $(a | b)")
	unsupported_plan(c"echo \"$(a)\"")
	unsupported_plan(c"echo `a`")
	unsupported_plan(c"echo $((1 + 2))")
	unsupported_plan(c"echo ${x:-$(a)}")
	unsupported_plan(c"if a; then b; fi")
	unsupported_plan(c"for x in a; do b; done")
	unsupported_plan(c"! a | b")
	unsupported_plan(c"echo a # |ignored")
	unsupported_plan(c"echo >$HOME")
	unsupported_plan(c"echo >\"$HOME\"")
	unsupported_plan(c"echo >*.w")
	unsupported_plan(c"echo >[ab]")
	unsupported_plan(c"echo >~user/file")
	# Even a malformed prefix must not conceal a later unsupported construct.
	unsupported_plan(c"echo > ; echo $(side_effect)")

void plan_ownership_and_scale_test():
	string_builder* input = string_from(c"echo 'owned' >'owned path'")
	shell_plan* p = checked_plan(input.data)
	assert_strings_equal(c"echo 'owned' >'owned path'", input.data)
	string_free(input)
	assert_strings_equal(c"echo 'owned'", p.pipelines[0].commands[0].text)
	assert_strings_equal(c"owned path", p.pipelines[0].commands[0].redirects[0].path)
	shell_plan_free(p)
	# Parsing must neither exit, print, open missing inputs, nor create outputs.
	p = checked_plan(c"echo 79; echo MUST_NOT_PRINT >/no-such-shell-plan-directory/out; cat </no-such-shell-plan-input")
	assert_equal(3, p.pipelines.length)
	shell_plan_free(p)
	input = string_new()
	for i in range(300):
		if (i): string_append(input, c" || ")
		string_append(input, c"echo 'a|b' >out 2>&1 | cat <in | wc")
	p = checked_plan(input.data)
	assert_equal(300, p.pipelines.length)
	for i in range(300):
		assert_equal(3, p.pipelines[i].commands.length)
		assert_equal(i == 0 ? 0 : 2, p.pipelines[i].condition)
		assert_strings_equal(c"echo 'a|b'", p.pipelines[i].commands[0].text)
		assert_equal(2, p.pipelines[i].commands[0].redirects.length)
	shell_plan_free(p)
	string_free(input)
	input = string_new()
	for i in range(1000):
		if (i): string_append(input, c"|")
		string_append(input, c"echo a")
	p = checked_plan(input.data)
	assert_equal(1000, p.pipelines[0].commands.length)
	shell_plan_free(p)
	string_free(input)
	shell_plan_free(0)

plan_syntax_test()
plan_quotes_test()
plan_redirect_test()
plan_adjacent_redirect_test()
plan_failures_test()
plan_ownership_and_scale_test()
