# Near-limit companion to tests/statement_nesting_error_fixture.w:
# grammar/statement.w's stmt_nesting_depth guard errors past 200 nested
# statement() recursions, so this 150-branch 'if'/'else if' chain (151
# total with the function's own top-level body) must still compile
# cleanly -- proving the limit does not clip legitimate (if extreme)
# real nesting. lib/lib.w's errno-to-string dispatch, the deepest
# in-tree 'else if' chain, is 132 branches -- under this fixture's
# depth too, so this is still a realistic upper bound, not a
# contrived one.
# reject_stderr: nesting too deep
void main():
	int x = 0
	if (x == 0): pass
	else if (x == 1): pass
	else if (x == 2): pass
	else if (x == 3): pass
	else if (x == 4): pass
	else if (x == 5): pass
	else if (x == 6): pass
	else if (x == 7): pass
	else if (x == 8): pass
	else if (x == 9): pass
	else if (x == 10): pass
	else if (x == 11): pass
	else if (x == 12): pass
	else if (x == 13): pass
	else if (x == 14): pass
	else if (x == 15): pass
	else if (x == 16): pass
	else if (x == 17): pass
	else if (x == 18): pass
	else if (x == 19): pass
	else if (x == 20): pass
	else if (x == 21): pass
	else if (x == 22): pass
	else if (x == 23): pass
	else if (x == 24): pass
	else if (x == 25): pass
	else if (x == 26): pass
	else if (x == 27): pass
	else if (x == 28): pass
	else if (x == 29): pass
	else if (x == 30): pass
	else if (x == 31): pass
	else if (x == 32): pass
	else if (x == 33): pass
	else if (x == 34): pass
	else if (x == 35): pass
	else if (x == 36): pass
	else if (x == 37): pass
	else if (x == 38): pass
	else if (x == 39): pass
	else if (x == 40): pass
	else if (x == 41): pass
	else if (x == 42): pass
	else if (x == 43): pass
	else if (x == 44): pass
	else if (x == 45): pass
	else if (x == 46): pass
	else if (x == 47): pass
	else if (x == 48): pass
	else if (x == 49): pass
	else if (x == 50): pass
	else if (x == 51): pass
	else if (x == 52): pass
	else if (x == 53): pass
	else if (x == 54): pass
	else if (x == 55): pass
	else if (x == 56): pass
	else if (x == 57): pass
	else if (x == 58): pass
	else if (x == 59): pass
	else if (x == 60): pass
	else if (x == 61): pass
	else if (x == 62): pass
	else if (x == 63): pass
	else if (x == 64): pass
	else if (x == 65): pass
	else if (x == 66): pass
	else if (x == 67): pass
	else if (x == 68): pass
	else if (x == 69): pass
	else if (x == 70): pass
	else if (x == 71): pass
	else if (x == 72): pass
	else if (x == 73): pass
	else if (x == 74): pass
	else if (x == 75): pass
	else if (x == 76): pass
	else if (x == 77): pass
	else if (x == 78): pass
	else if (x == 79): pass
	else if (x == 80): pass
	else if (x == 81): pass
	else if (x == 82): pass
	else if (x == 83): pass
	else if (x == 84): pass
	else if (x == 85): pass
	else if (x == 86): pass
	else if (x == 87): pass
	else if (x == 88): pass
	else if (x == 89): pass
	else if (x == 90): pass
	else if (x == 91): pass
	else if (x == 92): pass
	else if (x == 93): pass
	else if (x == 94): pass
	else if (x == 95): pass
	else if (x == 96): pass
	else if (x == 97): pass
	else if (x == 98): pass
	else if (x == 99): pass
	else if (x == 100): pass
	else if (x == 101): pass
	else if (x == 102): pass
	else if (x == 103): pass
	else if (x == 104): pass
	else if (x == 105): pass
	else if (x == 106): pass
	else if (x == 107): pass
	else if (x == 108): pass
	else if (x == 109): pass
	else if (x == 110): pass
	else if (x == 111): pass
	else if (x == 112): pass
	else if (x == 113): pass
	else if (x == 114): pass
	else if (x == 115): pass
	else if (x == 116): pass
	else if (x == 117): pass
	else if (x == 118): pass
	else if (x == 119): pass
	else if (x == 120): pass
	else if (x == 121): pass
	else if (x == 122): pass
	else if (x == 123): pass
	else if (x == 124): pass
	else if (x == 125): pass
	else if (x == 126): pass
	else if (x == 127): pass
	else if (x == 128): pass
	else if (x == 129): pass
	else if (x == 130): pass
	else if (x == 131): pass
	else if (x == 132): pass
	else if (x == 133): pass
	else if (x == 134): pass
	else if (x == 135): pass
	else if (x == 136): pass
	else if (x == 137): pass
	else if (x == 138): pass
	else if (x == 139): pass
	else if (x == 140): pass
	else if (x == 141): pass
	else if (x == 142): pass
	else if (x == 143): pass
	else if (x == 144): pass
	else if (x == 145): pass
	else if (x == 146): pass
	else if (x == 147): pass
	else if (x == 148): pass
	else if (x == 149): pass
