# wbuild: x64 tool=tools/wc2.w
import tests.wc2_support


void test_wc2_arithmetic_differential():
	wc2_test_differential(c"2 + 3 * 4", c"14")
	wc2_test_differential(c"(2 + 3) * 4", c"20")
	wc2_test_differential(c"20 - 5 - 3", c"12")
	wc2_test_differential(c"20 - (5 - 3)", c"18")
	wc2_test_differential(c"120 / 3 / 4", c"10")
	wc2_test_differential(c"-17 / 5", c"-3")
	wc2_test_differential(c"17 / -5", c"-3")
	wc2_test_differential(c"-17 % 5", c"-2")
	wc2_test_differential(c"17 % -5", c"2")
	wc2_test_differential(c"(100 / (3 + 2)) * (7 % 4) - 8", c"52")
	wc2_test_differential(c"+(-(-7))", c"7")
	wc2_test_differential(c"~0", c"-1")
	wc2_test_differential(c"2147483647 + 1", c"2147483648")
	wc2_test_differential(c"65536 * 65536", c"0")
	wc2_test_differential(c"4294967295", c"-1")
	wc2_test_differential(c"0xffffffff", c"-1")
	wc2_test_differential(c"0x80000000", c"-2147483648")
	wc2_test_differential(c"0b11111111111111111111111111111111", c"-1")
	wc2_test_differential(c"0000000000000000000000000000014", c"14")
	wc2_test_differential(c"1 << 31", c"2147483648")
	wc2_test_differential(c"-8 >> 2", c"-2")
	wc2_test_differential(c"1 << 33", c"2")
	wc2_test_differential(c"(0xabcd & 255) | (3 ^ 1)", c"207")
	wc2_test_differential(c"1 | 2 ^ 3 & 6", c"1")


void test_wc2_comparison_and_short_circuit_differential():
	wc2_test_differential(c"-1 < 1", c"1")
	wc2_test_differential(c"-1 > 1", c"0")
	wc2_test_differential(c"7 <= 7", c"1")
	wc2_test_differential(c"7 >= 7", c"1")
	wc2_test_differential(c"7 < 7", c"0")
	wc2_test_differential(c"7 > 7", c"0")
	wc2_test_differential(c"2147483648 < 2147483647", c"1")
	wc2_test_differential(c"65536 == 0", c"0")
	wc2_test_differential(c"65536 != 0", c"1")
	wc2_test_differential(c"!65536", c"0")
	wc2_test_differential(c"!0", c"1")
	wc2_test_differential(c"true && !false", c"1")
	wc2_test_differential(c"2 && 7", c"1")
	wc2_test_differential(c"2 || 7", c"1")
	wc2_test_differential(c"0 || 65536", c"1")
	wc2_test_differential(c"2 && 0", c"0")
	wc2_test_differential(c"0 && (1 / 0)", c"0")
	wc2_test_differential(c"9 || (1 / 0)", c"1")
	wc2_test_differential(c"1 && (0 || (5 < 7))", c"1")
	wc2_test_differential(c"(0 && (1 / 0)) + (1 || (1 / 0))", c"1")
	# Force a forward branch longer than rel8 and grow the image buffer
	# while its displacement is pending.
	string_builder* long_rhs = string_new()
	string_append(long_rhs, c"1 || (1 / 0")
	for i in range(40): string_append(long_rhs, c" + 1")
	string_append(long_rhs, c")")
	wc2_test_differential(long_rhs.data, c"1")
	string_free(long_rhs)


void test_wc2_executable_cli_and_layout():
	char* input = wc2_emit_test_path(c".w")
	char* output = wc2_emit_test_path(c".elf")
	char* source = c"int main(): return 2 + 3 * 4\n"
	assert1(file_write_text(input, source))
	process_result* compiled = wc2_test_compile(c"bin/wc2", input, output)
	assert_equal(0, compiled.status)
	assert_strings_equal(c"", compiled.stdout_text)
	assert_strings_equal(c"", compiled.stderr_text)
	process_result_free(compiled)
	wc2_test_exit(output, 14)
	wc2_module* m = wc2_parse(source, input)
	asm_buffer* image = wc2_emit(m)
	assert1(image != 0)
	# The x64 twin runs a 64-bit emitter, comparing every output byte with
	# the CLI's 32-bit emitter. Paths and addresses must not affect output.
	int fd = open(output, 0, 0)
	assert1(fd >= 0)
	assert_equal(image.length, file_size(fd))
	char* bytes = malloc(image.length)
	assert_equal(image.length, read_exact(fd, bytes, image.length))
	assert1(mem_eq(bytes, image.data, image.length))
	assert_equal(0x464c457f, load_int32(bytes))
	assert_equal(1, bytes[4])
	assert_equal(3, load_int16(bytes + 18))
	assert_equal(0x08048000 + 116, load_int32(bytes + 24))
	assert_equal(52, load_int32(bytes + 28))
	assert_equal(2, load_int16(bytes + 44))
	assert_equal(1, load_int32(bytes + 52))
	assert_equal(image.length, load_int32(bytes + 68))
	assert_equal(image.length, load_int32(bytes + 72))
	assert_equal(5, load_int32(bytes + 76))
	assert_equal(0x6474e551, load_int32(bytes + 84))
	assert_equal(6, load_int32(bytes + 108))
	close(fd)
	free(bytes)
	wc2_module_free(m)
	m = wc2_parse(source, c"a different filename.w")
	asm_buffer* again = wc2_emit(m)
	assert_equal(image.length, again.length)
	assert1(mem_eq(image.data, again.data, image.length))
	asm_buffer_free(again)
	asm_buffer_free(image)
	wc2_module_free(m)
	unlink(input)
	unlink(output)
	free(input)
	free(output)


void test_wc2_rejects_unsupported_executables():
	wc2_test_rejected(c"", c"requires int main()")
	wc2_test_rejected(c"int x = 1\n", c"top level currently supports functions only")
	wc2_test_rejected(c"int other(): return 1\n", c"requires int main()")
	wc2_test_rejected(c"bool main(): return true\n", c"requires int main()")
	wc2_test_rejected(c"int main(int x): return 1\n", c"requires int main()")
	wc2_test_rejected(c"int main():\n", c"may reach its end")
	wc2_test_rejected(c"int main(): return\n", c"must return a value")
	wc2_test_rejected(c"int main(): return x\n", c"unknown name")
	wc2_test_rejected(c"int main(): return 1 || unknown\n", c"unknown name")
	wc2_test_rejected(c"int main(): return 4294967296\n", c"exceeds 32 significant bits")
	wc2_test_rejected(c"int main(): return 0x100000000\n", c"exceeds 32 significant bits")
	wc2_test_rejected(c"int main(): return 0b100000000000000000000000000000000\n", c"exceeds 32 significant bits")
	string_builder* deep = string_new()
	string_append(deep, c"int main(): return 1")
	for i in range(205): string_append(deep, c" + 1")
	string_append(deep, c"\n")
	wc2_test_rejected(deep.data, c"executable expression nesting limit exceeded")
	string_free(deep)


void test_wc2_failed_compile_preserves_output():
	char* input = wc2_emit_test_path(c".w")
	char* output = wc2_emit_test_path(c".elf")
	assert1(file_write_text(output, c"previous executable"))
	assert1(file_write_text(input, c"int main(): return unknown\n"))
	process_result* failed = wc2_test_compile(c"bin/wc2", input, output)
	assert_equal(1, failed.status)
	assert_strings_equal(c"", failed.stdout_text)
	assert_contains(failed.stderr_text, c":1:20: wc2:")
	process_result_free(failed)
	char* old = file_read_text(output)
	assert_strings_equal(c"previous executable", old)
	free(old)
	assert1(file_write_text(input, c"int main(): return 14\n"))
	# Rename over a directory fails; the exclusive sibling must be removed.
	char* directory = wc2_emit_test_path(c".dir")
	assert_equal(0, mkdir(directory, 493))
	failed = wc2_test_compile(c"bin/wc2", input, directory)
	assert_equal(1, failed.status)
	assert_contains(failed.stderr_text, c"cannot write executable")
	process_result_free(failed)
	# Exercise the writer in this process too, so its temporary path is
	# known and cleanup/exclusive creation can be checked directly.
	wc2_module* m = wc2_parse(c"int main(): return 14\n", input)
	asm_buffer* image = wc2_emit(m)
	assert1(image != 0)
	assert_equal(0, wc2_write_executable(directory, image))
	string_builder* temporary = string_new()
	string_append(temporary, directory)
	string_append(temporary, c".wc2.")
	string_append_int(temporary, getpid())
	assert1(open(temporary.data, 0, 0) < 0)
	assert1(file_write_text(temporary.data, c"unrelated existing temporary"))
	assert_equal(0, wc2_write_executable(directory, image))
	char* untouched = file_read_text(temporary.data)
	assert_strings_equal(c"unrelated existing temporary", untouched)
	free(untouched)
	unlink(temporary.data)
	string_free(temporary)
	asm_buffer_free(image)
	wc2_module_free(m)
	assert_equal(0, rmdir(directory))
	failed = wc2_test_compile(c"bin/wc2", input, c"bin/no-such-wc2-directory/output")
	assert_equal(1, failed.status)
	assert_contains(failed.stderr_text, c"cannot write executable")
	process_result_free(failed)
	unlink(input)
	unlink(output)
	free(input)
	free(output)
	free(directory)
