# wbuild: x64
import libs.standard.sql.parser
import lib.assert


void sql_parser_expect(char* source, int valid, int count):
	sql_document* document = sql_document_parse(source, c"test.sql")
	asserts(source, sql_document_ok(document) == valid)
	assert_equal(count, sql_document_statement_count(document))
	char* rebuilt = pg_token_stream_source(document.tokens)
	assert_strings_equal(source, rebuilt)
	free(rebuilt)
	if (valid == 0): assert1(pg_diagnostics_count(document.diagnostics) > 0)
	sql_document_free(document)


int main():
	malloc_force_debug_mode()
	sql_parser_expect(c"", 1, 0)
	sql_parser_expect(c"; ; -- nothing here\n/* comment */", 1, 0)
	sql_parser_expect(c"sElEcT Users.Name, 'SELECT', 'O''Brien', \"a\"\"b\", 1.25e-3, .5 FROM Users", 1, 1)
	sql_parser_expect(c"SELECT selectivity, from_date, c, f FROM users;", 1, 1)
	sql_parser_expect(c"SELECT ?, ?1, $2, :name FROM users WHERE id = :id;", 1, 1)
	sql_parser_expect(c"SELECT 'back\\slash', \"back\\slash\";", 1, 1)
	sql_parser_expect(c"SELECT * FROM a LEFT JOIN b ON a.id = b.id WHERE a.id IN (SELECT id FROM c);", 1, 1)
	sql_parser_expect(c"SELECT dept, COUNT(*) FROM users GROUP BY dept HAVING COUNT(*) > 1 ORDER BY dept LIMIT 5;", 1, 1)
	sql_parser_expect(c"SELECT CASE WHEN 1 < 2 THEN 'yes' ELSE 'no' END, CAST(1 AS TEXT);", 1, 1)
	sql_parser_expect(c"SELECT 1 UNION ALL SELECT 2;", 1, 1)
	sql_parser_expect(c"CREATE TABLE items (id INT PRIMARY KEY, name TEXT NOT NULL); INSERT INTO items VALUES (1, 'Ada'); UPDATE items SET name = 'Grace' WHERE id = 1; DELETE FROM items WHERE id = 1; DROP TABLE items;", 1, 5)
	sql_parser_expect(c";; SELECT 1;;; SELECT 2 -- final statement needs no semicolon\n", 1, 2)
	sql_parser_expect(c"SELECT FROM users", 0, 0)
	sql_parser_expect(c"SELECT 1 SELECT 2", 0, 0)
	sql_parser_expect(c"SELECT 1; DELETE FROM", 0, 0)
	sql_parser_expect(c"SELECT @;", 0, 0)
	sql_parser_expect(c"SELECT 'unterminated", 0, 0)
	sql_parser_expect(c"SELECT \"unterminated", 0, 0)
	sql_parser_expect(c"SELECT 1; /* unterminated", 0, 0)
	sql_parser_expect(c"/*/", 0, 0)
	# Inputs may be freed immediately; spans/text/diagnostics stay valid.
	char* source = strclone(c"-- lead\nselect Name /* keep */ from Users; insert into Users values ('Ada')")
	char* filename = strclone(c"owned.sql")
	sql_document* document = sql_document_parse(source, filename)
	free(source)
	free(filename)
	assert1(sql_document_ok(document))
	assert_equal(2, sql_document_statement_count(document))
	assert1(sql_document_statement(document, -1) == 0)
	assert1(sql_document_statement(document, 2) == 0)
	pg_ast_node* statement = sql_document_statement(document, 0)
	assert_equal(sql_ast_select_stmt, statement.kind)
	assert_strings_equal(c"select_stmt", statement.name)
	pg_token* first = pg_ast_first_token(statement)
	assert_strings_equal(c"select", first.text)
	assert_strings_equal(c"owned.sql", first.filename)
	assert_equal(2, first.line)
	assert_equal(1, first.column)
	assert_equal(8, first.offset)
	assert_strings_equal(c"Users", pg_ast_last_token(statement).text)
	assert_equal(sql_ast_insert_stmt, sql_document_statement(document, 1).kind)
	# Freeing another parse cannot invalidate this document.
	sql_parser_expect(c"SELECT 2", 1, 1)
	assert_strings_equal(c"select", first.text)
	sql_document_free(document)
	document = sql_document_parse(c"SELECT 1;\nSELECT FROM users;", c"broken.sql")
	assert1(sql_document_ok(document) == 0)
	pg_diagnostic* diagnostic = pg_diagnostics_get(document.diagnostics, 0)
	assert_strings_equal(c"broken.sql", diagnostic.filename)
	assert_equal(2, diagnostic.line)
	assert_equal(8, diagnostic.column)
	sql_document_free(document)
	sql_document_free(0)
	assert_equal(0, debug_alloc_report_leaks())
	println(c"sql_parser_test: OK")
	return 0
