# wbuild: arch_only=x64
import libs.standard.sql.client
import lib.assert
import lib.file

void sql_test_exec(sql_connection* c, char* query):
	int ok = sql_exec(c, query)
	asserts(sql_error(c), ok)

int main():
	if (sql_sqlite_available() == 0):
		println(c"sql: SKIP SQLite (libsqlite3.so.0 unavailable)")
		return 0
	sql_connection* c = sql_open_sqlite(c":memory:")
	asserts(sql_error(c), sql_is_open(c))
	sql_test_exec(c, c"CREATE TABLE items(id INTEGER PRIMARY KEY, name TEXT, note TEXT)")
	char*[3] params
	params[0] = c"9223372036854775807"
	params[1] = c"Robert'); DROP TABLE items;--"
	params[2] = 0
	sql_result* r = sql_query_params(c, c"INSERT INTO items VALUES (?1, ?2, ?3)", 3, &params[0])
	asserts(sql_error(c), r != 0)
	assert_equal(1, r.affected)
	sql_result_free(r)
	r = sql_query(c, c"SELECT id, name, note, '', x'610062' AS raw FROM items")
	asserts(sql_error(c), r != 0)
	assert_equal(1, r.rows)
	assert_equal(5, r.columns)
	assert_strings_equal(c"id", sql_column_name(r, 0))
	assert_strings_equal(params[0], sql_value(r, 0, 0))
	assert_strings_equal(params[1], sql_value(r, 0, 1))
	assert_equal(-1, sql_value_length(r, 0, 2))
	assert1(sql_value(r, 0, 2) == 0)
	assert_equal(0, sql_value_length(r, 0, 3))
	assert1(sql_value(r, 0, 3) != 0)
	assert_equal(3, sql_value_length(r, 0, 4))
	assert_equal(0, sql_value(r, 0, 4)[1])
	assert_equal(98, sql_value(r, 0, 4)[2])
	assert_equal(-2, sql_value_length(r, -1, 0))
	assert1(sql_value(r, 0, 5) == 0)
	sql_result_free(r)
	assert1(sql_query(c, c"SELECT ?") == 0)
	assert1(sql_error(c)[0] != 0)
	assert1(sql_query(c, c"SELECT 1; INSERT INTO items VALUES(2,'bad','bad')") == 0)
	assert1(sql_query(c, c"not valid sql") == 0)
	assert1(sql_query(c, c" -- empty") == 0)
	assert1(sql_query_params(c, c"SELECT 1", 1, cast(char**, 0)) == 0)
	r = sql_query(c, c"SELECT 1; -- trailing comment")
	asserts(sql_error(c), r != 0)
	assert_strings_equal(c"", sql_error(c))
	sql_result_free(r)
	assert1(sql_begin(c))
	assert1(sql_begin(c) == 0)
	sql_test_exec(c, c"INSERT INTO items VALUES(2,'rollback','')")
	assert1(sql_rollback(c))
	assert1(sql_commit(c) == 0)
	assert1(sql_begin(c))
	sql_test_exec(c, c"INSERT INTO items VALUES(3,'commit','')")
	assert1(sql_commit(c))
	r = sql_query(c, c"SELECT count(*) FROM items")
	asserts(sql_error(c), r != 0)
	assert_strings_equal(c"2", sql_value(r, 0, 0))
	sql_close(c)
	# Results outlive both later queries and the connection.
	assert_strings_equal(c"2", sql_value(r, 0, 0))
	sql_result_free(r)
	c = sql_open_sqlite(c"/no/such/w-sql-directory/test.db")
	assert1(sql_is_open(c) == 0)
	assert1(sql_error(c)[0] != 0)
	sql_close(c)
	# Bound result limits reject, never truncate, and leave SQLite usable.
	c = sql_open_sqlite(c":memory:")
	assert1(sql_query(c, c"SELECT zeroblob(1048577)") == 0)
	r = sql_query(c, c"SELECT 42")
	asserts(sql_error(c), r != 0)
	assert_strings_equal(c"42", sql_value(r, 0, 0))
	sql_result_free(r)
	sql_close(c)
	# File persistence and rollback on disconnect.
	char* pid = itoa(getpid())
	char* path = strjoin(c"bin/sql_persistence_", pid)
	free(pid)
	int fd = open(path, 194, 384)    # O_RDWR | O_CREAT | O_EXCL
	assert1(fd >= 0)
	close(fd)
	c = sql_open_sqlite(path)
	asserts(sql_error(c), sql_is_open(c))
	sql_test_exec(c, c"CREATE TABLE persisted(value TEXT)")
	sql_test_exec(c, c"INSERT INTO persisted VALUES('original')")
	assert1(sql_begin(c))
	sql_test_exec(c, c"UPDATE persisted SET value='rolled back'")
	sql_close(c)
	c = sql_open_sqlite(path)
	r = sql_query(c, c"SELECT value FROM persisted")
	asserts(sql_error(c), r != 0)
	assert_strings_equal(c"original", sql_value(r, 0, 0))
	sql_result_free(r)
	r = sql_query(c, c"DELETE FROM persisted")
	asserts(sql_error(c), r != 0)
	assert_equal(1, r.affected)
	sql_result_free(r)
	r = sql_query(c, c"CREATE TABLE no_changes(value TEXT)")
	asserts(sql_error(c), r != 0)
	assert_equal(0, r.affected)
	sql_result_free(r)
	sql_close(c)
	assert_equal(0, unlink(path))
	free(path)
	sql_close(cast(sql_connection*, 0))
	sql_result_free(cast(sql_result*, 0))
	println(c"sql SQLite OK")
	return 0
