/*
graphics.ui.font: decodes the baked atlas (graphics/ui/font_data.w,
regenerated by ./wbuild ui_font_data from the committed Liberation
Sans faces) and measures proportional text. Strike 0 is 16 ppem
regular body text, strike 1 is 20 ppem bold titles; the theme's
text_scale token selects a strike through ui_font_strike_from_scale
(<= 2 body, else title). Alongside the glyphs the atlas carries the
antialiased masks the renderer's shape primitives sample — ids below,
in the order tools/generate_ui_atlas.w bakes them. Pure CPU code —
the GL upload lives in graphics.ui.render.
*/
import lib.lib
import graphics.ui.font_data


# Mask ids in atlas bake order.
int ui_mask_white():
	return 0


int ui_mask_corner():
	return 1


int ui_mask_disc():
	return 2


int ui_mask_ring():
	return 3


int ui_mask_check():
	return 4


int ui_mask_chevron():
	return 5


int ui_mask_shadow():
	return 6


# ui_render_mask mirrors but never rotates, so the 'v' chevron above
# cannot supply the right-pointing form a collapsed tree node needs.
# flip_x on this one gives the left-pointing form.
int ui_mask_chevron_right():
	return 7


int ui_mask_cross():
	return 8


# One glyph's (or mask's) atlas rect and pixel metrics. bearing_x is
# the pen-to-bitmap x offset; bearing_top is rows above the baseline
# (negative for below-baseline ink like '_').
struct ui_glyph:
	int32 x
	int32 y
	int32 w
	int32 h
	int32 advance
	int32 bearing_x
	int32 bearing_top


ui_glyph ui_font_decode(char* record):
	ui_glyph g
	g.x = (record[0] & 255) | ((record[1] & 255) << 8)
	g.y = (record[2] & 255) | ((record[3] & 255) << 8)
	g.w = record[4] & 255
	g.h = record[5] & 255
	g.advance = record[6] & 255
	g.bearing_x = (record[7] & 255) - 8
	g.bearing_top = (record[8] & 255) - 8
	return g


int ui_font_strike_from_scale(int scale):
	if (scale <= 2):
		return 0
	return 1


ui_glyph ui_font_glyph(int strike, int ch):
	return ui_font_decode(ui_font_glyph_record(strike, ch))


ui_glyph ui_font_mask(int mask):
	return ui_font_decode(ui_font_mask_record(mask))


# Build the atlas pixel buffer (ui_font_atlas_w x ui_font_atlas_h
# coverage bytes) by expanding the RLE chunk stream (tag 0: zero run,
# tag 1: 255 run, tag 2: literal run). Caller frees.
char* ui_font_build_atlas():
	int rle_length = ui_font_rle_length()
	char* stream = malloc(rle_length)
	int chunk_size = ui_font_rle_chunk_size()
	int i = 0
	while (i < ui_font_rle_chunk_count()):
		char* chunk = ui_font_rle_chunk(i)
		int base = i * chunk_size
		int count = rle_length - base
		if (count > chunk_size):
			count = chunk_size
		int j = 0
		while (j < count):
			stream[base + j] = chunk[j]
			j = j + 1
		i = i + 1

	int total = ui_font_atlas_w() * ui_font_atlas_h()
	char* pixels = malloc(total)
	int pos = 0
	int out = 0
	while ((pos + 1 < rle_length) && (out < total)):
		int tag = stream[pos] & 255
		int count2 = stream[pos + 1] & 255
		pos = pos + 2
		if (out + count2 > total):
			count2 = total - out
		int k = 0
		if (tag == 0):
			while (k < count2):
				pixels[out + k] = 0
				k = k + 1
		else if (tag == 1):
			while (k < count2):
				pixels[out + k] = 255
				k = k + 1
		else:
			while (k < count2):
				pixels[out + k] = stream[pos + k]
				k = k + 1
			pos = pos + count2
		out = out + count2
	free(stream)
	return pixels


# Proportional pixel width of a string at the strike text_scale
# selects.
int ui_text_width(char* s, int scale):
	int strike = ui_font_strike_from_scale(scale)
	int width = 0
	int i = 0
	while (s[i] != 0):
		ui_glyph g = ui_font_glyph(strike, s[i] & 255)
		width = width + g.advance
		i = i + 1
	return width


# Line-box height (ascent + descent) of the strike.
int ui_text_height(int scale):
	int strike = ui_font_strike_from_scale(scale)
	return ui_font_ascent(strike) + ui_font_descent(strike)


# Width of the first count bytes (caret positioning).
int ui_text_prefix_width(char* s, int count, int scale):
	int strike = ui_font_strike_from_scale(scale)
	int width = 0
	int i = 0
	while ((i < count) && (s[i] != 0)):
		ui_glyph g = ui_font_glyph(strike, s[i] & 255)
		width = width + g.advance
		i = i + 1
	return width


# Nearest glyph boundary to the pixel offset x_rel from the string's
# left edge (caret placement from a click).
int ui_text_caret_from_x(char* s, int scale, int x_rel):
	int strike = ui_font_strike_from_scale(scale)
	int acc = 0
	int i = 0
	while (s[i] != 0):
		ui_glyph g = ui_font_glyph(strike, s[i] & 255)
		if (x_rel < acc + g.advance / 2):
			return i
		acc = acc + g.advance
		i = i + 1
	return i
