# wbuild: name=javascript_standards_early_test
# wbuild: target=javascript_standards_early_test tag=tests dep=javascript_parser
# wbuild: step="bin/wv2 tests/javascript/standards_early_test.w -o bin/javascript_standards_early_test"
# wbuild: step="bin/javascript_standards_early_test"
import lib.testing
import libs.extras.javascript.parser


void js_standard_early(char* source, int module, int expected):
	pg_parse_result* result = js_parse(source, strlen(source), c"standards.js", module)
	if (result.success != expected):
		println2(source)
		pg_diagnostics_print(result.diagnostics)
	assert_equal(expected, result.success)
	pg_parse_result_free(result)


void test_js_async_generator_formals():
	js_standard_early(c"async function f(x = await 1) {}", 0, 0)
	js_standard_early(c"function* f(x = yield 1) {}", 0, 0)
	js_standard_early(c"async function* f(x = yield 1) {}", 0, 0)
	js_standard_early(c"async function* f(x = await 1) {}", 0, 0)
	js_standard_early(c"const f = async (x = await 1) => x;", 0, 0)
	js_standard_early(c"const o = {async f(x = await 1) {}};", 0, 0)
	js_standard_early(c"const o = {*f(x = yield 1) {}};", 0, 0)
	js_standard_early(c"async function f({[await 1]: x}) {}", 0, 0)
	js_standard_early(c"function* f([x = yield 1]) {}", 0, 0)
	js_standard_early(c"async function f(x,x) {}", 0, 0)
	js_standard_early(c"function* f(x,x) {}", 0, 0)
	js_standard_early(c"async function* f(x,x) {}", 0, 0)
	js_standard_early(c"const f = async function(x,x) {};", 0, 0)
	js_standard_early(c"const f = function*(x,x) {};", 0, 0)
	js_standard_early(c"async function f(x,\\u0078) {}", 0, 0)
	# Nested function bodies establish their own await/yield context.
	js_standard_early(c"async function f(x = async function(){ await 1; }) {}", 0, 1)
	js_standard_early(c"function* f(x = function*(){ yield 1; }) {}", 0, 1)
	js_standard_early(c"async function f(x = async () => await 1) {}", 0, 1)
	js_standard_early(c"async function f(x = {async m(){await 1;}}) {}", 0, 1)
	js_standard_early(c"function* f(x = { *m(){yield 1;} }) {}", 0, 1)
	js_standard_early(c"function f(x,x) {}", 0, 1)
	js_standard_early(c"async function f(x,y) { await x; }", 0, 1)
	js_standard_early(c"function* f(x,y) { yield x; }", 0, 1)


void test_js_exported_names_and_local_bindings():
	js_standard_early(c"export {missing};", 1, 0)
	js_standard_early(c"export {missing as visible};", 1, 0)
	js_standard_early(c"export default 1; export default 2;", 1, 0)
	js_standard_early(c"const x=1; export {x}; export {x};", 1, 0)
	js_standard_early(c"export const x=1; export {x};", 1, 0)
	js_standard_early(c"export function f(){} export {f};", 1, 0)
	js_standard_early(c"export class C{} export {C};", 1, 0)
	js_standard_early(c"export let {x,y:z} = value; export {z};", 1, 0)
	js_standard_early(c"export default 1; const x=2; export {x as default};", 1, 0)
	js_standard_early(c"export {x as same} from 'a'; export {y as same} from 'b';", 1, 0)
	js_standard_early(c"export * as same from 'a'; export * as same from 'b';", 1, 0)
	js_standard_early(c"export * as default from 'a'; export default 1;", 1, 0)
	js_standard_early(c"export {x}; {let x;}", 1, 0)
	js_standard_early(c"export {x}; function f(){var x;}", 1, 0)
	js_standard_early(c"const x=1; export {x as a, x as \\u0061};", 1, 0)
	js_standard_early(c"export {x}; const x=1;", 1, 1)
	js_standard_early(c"export {x}; {var x;}", 1, 1)
	js_standard_early(c"export {x as a, x as b}; let x;", 1, 1)
	js_standard_early(c"export {x}; import {x} from 'a';", 1, 1)
	js_standard_early(c"export {x}; import {other as x} from 'a';", 1, 1)
	js_standard_early(c"export {ns}; import * as ns from 'a';", 1, 1)
	js_standard_early(c"export {x}; import x from 'a';", 1, 1)
	js_standard_early(c"export {f}; export default function f() {}", 1, 1)
	js_standard_early(c"export {C}; export default class C {}", 1, 1)
	js_standard_early(c"export {missing} from 'a';", 1, 1)
	js_standard_early(c"export {default as x} from 'a';", 1, 1)
	js_standard_early(c"export * from 'a'; export * from 'b';", 1, 1)
	js_standard_early(c"export default function(){}", 1, 1)
	js_standard_early(c"export let {x,y:z} = value;", 1, 1)
	js_standard_early(c"let \\u0078; export {x};", 1, 1)


void test_js_chained_iteration_labels():
	js_standard_early(c"a: b: while(false) { continue a; }", 0, 1)
	js_standard_early(c"a: b: c: for (;;) { continue a; continue b; continue c; }", 0, 1)
	js_standard_early(c"a: b: do {continue a;} while(false);", 0, 1)
	js_standard_early(c"a: b: while(false) { continue \\u0061; }", 0, 1)
	js_standard_early(c"\\u0061: b: while(false) { continue a; }", 0, 1)
	js_standard_early(c"a: b: { while(false) { continue a; } }", 0, 0)
	js_standard_early(c"a: b: while(false) { function f(){ continue a; } }", 0, 0)
	js_standard_early(c"a: b: while(false) { continue missing; }", 0, 0)
	js_standard_early(c"a: b: {break a;}", 0, 1)
	js_standard_early(c"a: \\u0061: while(false) {}", 0, 0)


void test_js_regexp_structure_errors():
	js_standard_early(c"/(/;", 0, 0)
	js_standard_early(c"/)/;", 0, 0)
	js_standard_early(c"/(?:/;", 0, 0)
	js_standard_early(c"/(?z)/;", 0, 0)
	js_standard_early(c"/*a/;", 0, 0)
	js_standard_early(c"/+a/;", 0, 0)
	js_standard_early(c"/a**/;", 0, 0)
	js_standard_early(c"/a+*/;", 0, 0)
	js_standard_early(c"/^*/;", 0, 0)
	js_standard_early(c"/\\b+/;", 0, 0)
	js_standard_early(c"/a{3,2}/;", 0, 0)
	js_standard_early(c"/a{999999999999999999999,888888888888888888888}/;", 0, 0)
	js_standard_early(c"/a{0003,002}/;", 0, 0)
	js_standard_early(c"/a{2,3}*/;", 0, 0)
	js_standard_early(c"/(?=a)+/u;", 0, 0)
	js_standard_early(c"/(?<=a)+/;", 0, 0)
	js_standard_early(c"/(?<!a)?/;", 0, 0)
	js_standard_early(c"/a{bad}/u;", 0, 0)
	js_standard_early(c"/]/u;", 0, 0)
	js_standard_early(c"/(?<>a)/;", 0, 0)
	js_standard_early(c"/(a|b(?:c|))*/;", 0, 1)
	js_standard_early(c"/[(){}*+?]+/;", 0, 1)
	js_standard_early(c"/\\(\\)\\[\\]\\{\\}/u;", 0, 1)
	js_standard_early(c"/[\\]()]*/;", 0, 1)
	js_standard_early(c"/[]/; /[^]/;", 0, 1)
	js_standard_early(c"/a{2,3}?b*?c+?d??/;", 0, 1)
	js_standard_early(c"/a{0,}/; /a{2}/; /a{0002,003}/;", 0, 1)
	js_standard_early(c"/a{999999999999999999999,1000000000000000000000}/;", 0, 1)
	js_standard_early(c"/(?=a)+/; /(?=a)?/; /(?!a){2}/;", 0, 1)
	js_standard_early(c"/(?<=a)b/; /(?<!a)b/;", 0, 1)
	js_standard_early(c"/(?<name>a)\\k<name>/u;", 0, 1)
	js_standard_early(c"/\\u{28}*/u; /\\p{L}+/u;", 0, 1)
	js_standard_early(c"/a{bad}/; /]/; /}/;", 0, 1)
	js_standard_early(c"/^$|a||b/; /(?:)/;", 0, 1)
	js_standard_early(c"/\\/*/;", 0, 1)
