# Emits graphics/ui/font_data.w from the committed glyph asset
# tools/ui/font8x8.txt (public-domain dhepper/font8x8, ASCII 32..126).
#
# The data lands as c"\x.." byte-string chunk functions rather than an
# int array — the lib/sha256.w table precedent; large int literals with
# bit 31 set parse differently on the 32-bit seed, byte strings do not.
#
# Run from the repo root: ./wbuild ui_font_data
import lib.lib
import lib.stream
import structures.string


int gen_glyph_count():
	return 95


int gen_glyphs_per_chunk():
	return 32


int gen_hex_digit(int c):
	if ((c >= 48) && (c <= 57)):
		return c - 48
	if ((c >= 97) && (c <= 102)):
		return c - 87
	if ((c >= 65) && (c <= 70)):
		return c - 55
	return 0 - 1


# Parse the asset into 760 raw row bytes. Returns 0 on any format
# error (wrong glyph count, malformed hex).
char* gen_load_glyphs(char* path):
	wstream* in = stream_open_read(path)
	if (in == 0):
		return 0
	char* rows = malloc(gen_glyph_count() * 8)
	int filled = 0
	string_builder* line = string_new()
	while (stream_read_line(in, line)):
		char* text = line.data
		if ((line.length == 0) || (text[0] == 35)):
			continue
		# 8 space-separated hex byte pairs per glyph line.
		int pos = 0
		int parsed = 0
		while (parsed < 8):
			while ((pos < line.length) && (text[pos] == 32)):
				pos = pos + 1
			if (pos + 1 >= line.length):
				stream_close(in)
				return 0
			int hi = gen_hex_digit(text[pos] & 255)
			int lo = gen_hex_digit(text[pos + 1] & 255)
			if ((hi < 0) || (lo < 0)):
				stream_close(in)
				return 0
			if (filled >= gen_glyph_count() * 8):
				stream_close(in)
				return 0
			rows[filled] = hi * 16 + lo
			filled = filled + 1
			pos = pos + 2
			parsed = parsed + 1
	stream_close(in)
	if (filled != gen_glyph_count() * 8):
		return 0
	return rows


# Append one byte as a \xHH escape.
void gen_append_escape(string_builder* out, int value):
	string_append_char(out, 92)
	string_append_char(out, 120)
	int hi = (value >> 4) & 15
	int lo = value & 15
	if (hi < 10):
		string_append_char(out, 48 + hi)
	else:
		string_append_char(out, 87 + hi)
	if (lo < 10):
		string_append_char(out, 48 + lo)
	else:
		string_append_char(out, 87 + lo)


void gen_emit_chunk(wstream* out, char* rows, int chunk):
	int first = chunk * gen_glyphs_per_chunk()
	int last = first + gen_glyphs_per_chunk() - 1
	if (last >= gen_glyph_count()):
		last = gen_glyph_count() - 1
	stream_write_line(out, c"")
	stream_write_line(out, c"")
	stream_write_cstr(out, c"# Glyphs for characters ")
	stream_write_int(out, 32 + first)
	stream_write_cstr(out, c"..")
	stream_write_int(out, 32 + last)
	stream_write_cstr(out, c" (")
	stream_write_int(out, (last - first + 1) * 8)
	stream_write_line(out, c" bytes).")
	stream_write_cstr(out, c"char* ui_font_chunk_")
	stream_write_int(out, chunk)
	stream_write_line(out, c"():")
	string_builder* literal = string_new()
	string_append(literal, c"\treturn c\"")
	int i = first * 8
	while (i < (last + 1) * 8):
		gen_append_escape(literal, rows[i] & 255)
		i = i + 1
	string_append(literal, c"\"")
	stream_write_line(out, literal.data)


int main(int argc, int argv):
	char* rows = gen_load_glyphs(c"tools/ui/font8x8.txt")
	if (rows == 0):
		wstream* err = stderr_writer()
		stream_write_line(err, c"cannot load tools/ui/font8x8.txt (run from the repo root; 95 glyph lines of 8 hex bytes)")
		stream_flush(err)
		return 1
	wstream* out = stream_open_write(c"graphics/ui/font_data.w")
	stream_write_line(out, c"# GENERATED by tools/generate_ui_font.w from tools/ui/font8x8.txt —")
	stream_write_line(out, c"# do not edit by hand; run ./wbuild ui_font_data to regenerate.")
	stream_write_line(out, c"#")
	stream_write_line(out, c"# 8x8 ASCII glyphs, characters 32..126: 95 glyphs x 8 row bytes as")
	stream_write_line(out, c"# byte-string chunks (the lib/sha256.w table idiom). Top row first;")
	stream_write_line(out, c"# bit 0 of each row byte is the LEFTMOST pixel column.")
	stream_write_line(out, c"")
	stream_write_line(out, c"")
	stream_write_line(out, c"int ui_font_glyph_w():")
	stream_write_line(out, c"\treturn 8")
	stream_write_line(out, c"")
	stream_write_line(out, c"")
	stream_write_line(out, c"int ui_font_glyph_h():")
	stream_write_line(out, c"\treturn 8")
	stream_write_line(out, c"")
	stream_write_line(out, c"")
	stream_write_line(out, c"int ui_font_first_char():")
	stream_write_line(out, c"\treturn 32")
	stream_write_line(out, c"")
	stream_write_line(out, c"")
	stream_write_line(out, c"int ui_font_char_count():")
	stream_write_line(out, c"\treturn 95")
	gen_emit_chunk(out, rows, 0)
	gen_emit_chunk(out, rows, 1)
	gen_emit_chunk(out, rows, 2)
	stream_write_line(out, c"")
	stream_write_line(out, c"")
	stream_write_line(out, c"# Row bytes for one character; anything outside 32..126 maps to the")
	stream_write_line(out, c"# space glyph.")
	stream_write_line(out, c"char* ui_font_glyph_bits(int ch):")
	stream_write_line(out, c"\tint index = ch - 32")
	stream_write_line(out, c"\tif ((index < 0) || (index >= 95)):")
	stream_write_line(out, c"\t\tindex = 0")
	stream_write_line(out, c"\tchar* chunk = 0")
	stream_write_line(out, c"\tif (index < 32):")
	stream_write_line(out, c"\t\tchunk = ui_font_chunk_0()")
	stream_write_line(out, c"\telse if (index < 64):")
	stream_write_line(out, c"\t\tchunk = ui_font_chunk_1()")
	stream_write_line(out, c"\t\tindex = index - 32")
	stream_write_line(out, c"\telse:")
	stream_write_line(out, c"\t\tchunk = ui_font_chunk_2()")
	stream_write_line(out, c"\t\tindex = index - 64")
	stream_write_line(out, c"\treturn &chunk[index * 8]")
	stream_close(out)
	println2(c"generated graphics/ui/font_data.w")
	return 0
