#!/usr/bin/env python3
"""Emit lib/grapheme_data.w from Python's bundled Unicode database.

The generator intentionally stays offline. Python's unicodedata module gives us
portable ranges for combining marks and spacing marks; the remaining UAX #29
classes used by lib.grapheme are compact algorithmic ranges.
"""

import unicodedata
from pathlib import Path


SOURCE = Path("lib/grapheme_data.w")
MAX_CODEPOINT = 0x10FFFF


PREPEND_RANGES = (
	(0x0600, 0x0605),
	(0x06DD, 0x06DD),
	(0x070F, 0x070F),
	(0x0890, 0x0891),
	(0x08E2, 0x08E2),
	(0x110BD, 0x110BD),
	(0x110CD, 0x110CD),
)


def ranges_for(predicate):
	ranges = []
	start = None
	prev = None
	for cp in range(MAX_CODEPOINT + 1):
		if predicate(cp):
			if start is None:
				start = cp
			prev = cp
		elif start is not None:
			ranges.append((start, prev))
			start = None
	if start is not None:
		ranges.append((start, prev))
	return ranges


def category(cp):
	return unicodedata.category(chr(cp))


def is_control(cp):
	return category(cp) in ("Cc", "Zl", "Zp")


def is_extend(cp):
	return category(cp) in ("Mn", "Me")


def is_spacing_mark(cp):
	return category(cp) == "Mc"


def emit_range_checks(lines, ranges, prop):
	for start, end in ranges:
		if start == end:
			lines.append(f"\tif (cp == {start}):")
		else:
			lines.append(f"\tif (grapheme_in_range(cp, {start}, {end})):")
		lines.append(f"\t\treturn {prop}")


def main():
	control_ranges = ranges_for(is_control)
	extend_ranges = ranges_for(is_extend)
	spacing_mark_ranges = ranges_for(is_spacing_mark)

	lines = [
		"# Generated by tools/generate_grapheme_data.py from Python unicodedata",
		f"# version {unicodedata.unidata_version}.",
		"",
		"",
		"int grapheme_prop_other():",
		"\treturn 0",
		"",
		"",
		"int grapheme_prop_cr():",
		"\treturn 1",
		"",
		"",
		"int grapheme_prop_lf():",
		"\treturn 2",
		"",
		"",
		"int grapheme_prop_control():",
		"\treturn 3",
		"",
		"",
		"int grapheme_prop_extend():",
		"\treturn 4",
		"",
		"",
		"int grapheme_prop_zwj():",
		"\treturn 5",
		"",
		"",
		"int grapheme_prop_spacing_mark():",
		"\treturn 6",
		"",
		"",
		"int grapheme_prop_prepend():",
		"\treturn 7",
		"",
		"",
		"int grapheme_prop_l():",
		"\treturn 8",
		"",
		"",
		"int grapheme_prop_v():",
		"\treturn 9",
		"",
		"",
		"int grapheme_prop_t():",
		"\treturn 10",
		"",
		"",
		"int grapheme_prop_lv():",
		"\treturn 11",
		"",
		"",
		"int grapheme_prop_lvt():",
		"\treturn 12",
		"",
		"",
		"int grapheme_prop_regional_indicator():",
		"\treturn 13",
		"",
		"",
		"int grapheme_prop_extended_pictographic():",
		"\treturn 14",
		"",
		"",
		"int grapheme_in_range(int cp, int start, int end):",
		"\treturn (cp >= start) & (cp <= end)",
		"",
		"",
		"int grapheme_is_extended_pictographic(int cp):",
		"\tif (grapheme_in_range(cp, 9728, 10175)):",
		"\t\treturn 1",
		"\tif (grapheme_in_range(cp, 127744, 129791)):",
		"\t\treturn 1",
		"\treturn 0",
		"",
		"",
		"int grapheme_property(int cp):",
		"\tif (cp == 13):",
		"\t\treturn grapheme_prop_cr()",
		"\tif (cp == 10):",
		"\t\treturn grapheme_prop_lf()",
		"\tif (cp == 8205):",
		"\t\treturn grapheme_prop_zwj()",
	]
	emit_range_checks(lines, PREPEND_RANGES, "grapheme_prop_prepend()")
	emit_range_checks(lines, control_ranges, "grapheme_prop_control()")
	emit_range_checks(lines, extend_ranges, "grapheme_prop_extend()")
	emit_range_checks(lines, spacing_mark_ranges, "grapheme_prop_spacing_mark()")
	lines.extend(
		[
			"\tif (grapheme_in_range(cp, 4352, 4447)):",
			"\t\treturn grapheme_prop_l()",
			"\tif (grapheme_in_range(cp, 4448, 4519)):",
			"\t\treturn grapheme_prop_v()",
			"\tif (grapheme_in_range(cp, 4520, 4607)):",
			"\t\treturn grapheme_prop_t()",
			"\tif (grapheme_in_range(cp, 44032, 55203)):",
			"\t\tif (((cp - 44032) % 28) == 0):",
			"\t\t\treturn grapheme_prop_lv()",
			"\t\treturn grapheme_prop_lvt()",
			"\tif (grapheme_in_range(cp, 127462, 127487)):",
			"\t\treturn grapheme_prop_regional_indicator()",
			"\tif (grapheme_is_extended_pictographic(cp)):",
			"\t\treturn grapheme_prop_extended_pictographic()",
			"\treturn grapheme_prop_other()",
		]
	)
	SOURCE.write_text("\n".join(lines) + "\n")
	print(f"generated {SOURCE}")


if __name__ == "__main__":
	raise SystemExit(main())
