#!/usr/bin/env python3
"""Regenerate the JavaScript identifier tables from the vendored Unicode subset."""
from pathlib import Path
import argparse

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "libs/extras/javascript/unicode_12_1.ranges"
OUTPUT = ROOT / "libs/extras/javascript/unicode.w"


def generate():
    props = {"ID_Start": [], "ID_Continue": []}
    for line in DATA.read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        span, prop = line.split(";")
        lo, hi = (int(x, 16) for x in span.split(".."))
        props[prop].append((lo, hi))
    lines = [
        "# Generated by tools/javascript_unicode.py; Unicode 12.1.0.",
        "# Copyright Unicode, Inc.; see UNICODE-LICENSE.txt and unicode_12_1.ranges.",
        "import lib.lib", "", "",
        "int js_unicode_u24(char* data, int offset):",
        "\treturn (data[offset] & 255) | ((data[offset + 1] & 255) << 8) | ((data[offset + 2] & 255) << 16)",
        "", "",
        "int js_unicode_contains(char* data, int count, int codepoint):",
        "\tint lo = 0", "\tint hi = count",
        "\twhile (lo < hi):", "\t\tint mid = lo + (hi - lo) / 2",
        "\t\tint first = js_unicode_u24(data, mid * 6)",
        "\t\tint last = js_unicode_u24(data, mid * 6 + 3)",
        "\t\tif (codepoint < first): hi = mid",
        "\t\telse if (codepoint > last): lo = mid + 1",
        "\t\telse: return 1", "\treturn 0", "", "",
    ]
    for prop, spans in props.items():
        merged = []
        for lo, hi in spans:
            if merged and lo == merged[-1][1] + 1:
                merged[-1] = (merged[-1][0], hi)
            else:
                merged.append((lo, hi))
        raw = b"".join(n.to_bytes(3, "little") for pair in merged for n in pair)
        escaped = "".join(f"\\x{b:02x}" for b in raw)
        lines += [f"int js_unicode_{prop.lower()}(int codepoint):",
                  f'\tchar* data = c"{escaped}"',
                  f"\treturn js_unicode_contains(data, {len(merged)}, codepoint)", "", ""]
    return "\n".join(lines).rstrip() + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate()
    if args.check:
        if OUTPUT.read_text() != result:
            raise SystemExit("JavaScript Unicode tables need regeneration")
    else:
        OUTPUT.write_text(result)
