# wbuild: binary=libref
# wbuild: target=library_reference dep=wv2 dep=libref
# wbuild: step="bin/libref bin/library_reference.md" expect_stdout="libref: wrote bin/library_reference.md"
# wbuild: target=library_reference_test tag=tests dep=wv2 dep=libref data=lib/ data=structures/
# wbuild: step="bin/libref bin/library_reference_test.md" expect_stdout="libref: wrote bin/library_reference_test.md"
# wbuild: step="grep -F -q '## structures/heap.w' bin/library_reference_test.md"
# wbuild: step="grep -F -q 'heap_push[T](' bin/library_reference_test.md"
# wbuild: step="grep -F -q 'char* path_join(char* ' bin/library_reference_test.md"
/*
libref: generate the reference for the standard library (lib/) and the
container runtimes (structures/).

	libref <out.md>

'./wbuild library_reference' runs it as 'bin/libref
bin/library_reference.md'. Run it from the repository root, after
bin/wv2 exists. For every module, meaning each .w file under lib/ and
structures/ except tests (*_test.w), the per-target __arch__/ trees and
generated files, it runs 'bin/wv2 symbols --json <module>'. If that
fails it retries with the x64 target, for the float64 and int64
modules. It keeps the records declared in the module's own file and
renders, in source order:

  - functions, using the declaration line exactly as written in the
    source, so parameter names and defaults show;
  - types (struct, union, enum, type alias), with struct fields taken
    from the symbols record;
  - constants and globals;

each with the first paragraph of the comment directly above it, if any.
A module's summary is the first paragraph of its leading comment.
Names that start with '_' are internal and skipped. Generic
instantiations ('name$int') fold into their template's declaration
line, and generic templates that the module never instantiates (which
'symbols' does not report) are found by scanning the source.

The output is a build product in bin/, not a committed file, for three
reasons. It is large (about 420 KB, 5,900 lines). Producing it runs the
compiler once per module, about 140 runs, which takes 30 to 90
seconds. And it would have to change with every signature or
doc-comment edit in about 140 modules, so concurrent pull requests that
touch lib/ would keep conflicting on it. library_reference_test (part
of 'tests') instead checks that generation keeps working.
*/
import lib.lib
import lib.str
import lib.file
import lib.path
import lib.dir
import lib.process
import structures.string
import structures.json


# One rendered declaration of a module.
struct libref_decl:
	int line
	int group        # 0 function, 1 type, 2 constant or global
	char* text       # the declaration as written
	char* doc        # first paragraph of its comment, or 0
	char* extra      # struct/union field list, or 0


int libref_is_space(int c):
	return (c == ' ') || (c == 9) || (c == 13) || (c == 10)


# A trimmed, owned copy of s[start:end].
char* libref_trim_range(char* s, int start, int end):
	while ((start < end) && libref_is_space(s[start])): start = start + 1
	while ((end > start) && libref_is_space(s[end - 1])): end = end - 1
	return substring(s, start, end)


char* libref_trim(char* s):
	return libref_trim_range(s, 0, strlen(s))


int libref_starts(char* s, char* prefix):
	return starts_with(s, prefix)


# Should this repository path be documented as a module?
int libref_wanted(char* path):
	if (ends_with(path, c".w") == 0): return 0
	if (ends_with(path, c"_test.w")): return 0
	if (index_of(path, c"/__arch__/") >= 0): return 0
	# Generated data tables are build outputs, not committed sources
	# (lib/grapheme_data.w): their first line says so.
	list[char*] lines = file_read_lines(path)
	if (lines == 0): return 0
	int generated = 0
	if (lines.length > 0):
		if (libref_starts(lines[0], c"# Generated by")): generated = 1
	for char* l in lines: free(l)
	lines.free()
	return generated == 0


# Joins a comment paragraph's lines with single spaces.
void libref_append_words(string_builder* out, char* text):
	char* t = libref_trim(text)
	if (t[0] != 0):
		if (out.length > 0): string_append_char(out, ' ')
		string_append(out, t)
	free(t)


# The text of one comment line with its marker removed: '#', '/*', '*/'
# and a leading ' * ' continuation.
char* libref_comment_body(char* line):
	char* t = libref_trim(line)
	int start = 0
	int end = strlen(t)
	if (libref_starts(t, c"/*")): start = 2
	else if (t[0] == '#'): start = 1
	else if (libref_starts(t, c"* ")): start = 2
	else if (strcmp(t, c"*") == 0): start = 1
	if ((end - start >= 2) && (t[end - 2] == '*') && (t[end - 1] == '/')): end = end - 2
	char* body = libref_trim_range(t, start, end)
	free(t)
	return body


# The first paragraph of the comment lines[first..last] (0-based,
# inclusive), joined into one line, or 0 when it is empty.
char* libref_paragraph(list[char*] lines, int first, int last):
	string_builder* out = string_new()
	int i = first
	while (i <= last):
		char* body = libref_comment_body(lines[i])
		int blank = body[0] == 0
		# '# wbuild:' directives are build metadata, not prose.
		int directive = libref_starts(body, c"wbuild:")
		if (blank && (out.length > 0)):
			free(body)
			break
		if ((blank == 0) && (directive == 0)): libref_append_words(out, body)
		free(body)
		i = i + 1
	if (out.length == 0):
		string_free(out)
		return 0
	char* text = strclone(out.data)
	string_free(out)
	return text


# The comment directly above 1-based source line 'line': a run of '#'
# lines, or a '/* ... */' block whose '*/' ends the previous line.
char* libref_doc_above(list[char*] lines, int line):
	int last = line - 2
	if ((last < 0) || (last >= lines.length)): return 0
	char* above = libref_trim(lines[last])
	int is_hash = above[0] == '#'
	int is_block = ends_with(above, c"*/")
	free(above)
	int first = last
	if (is_hash):
		while (first > 0):
			char* prev = libref_trim(lines[first - 1])
			int hash = prev[0] == '#'
			free(prev)
			if (hash == 0): break
			first = first - 1
		return libref_paragraph(lines, first, last)
	if (is_block):
		while (first >= 0):
			if (index_of(lines[first], c"/*") >= 0): break
			first = first - 1
		if (first < 0): return 0
		return libref_paragraph(lines, first, last)
	return 0


# A module's summary: the first paragraph of the comment that opens
# the file (after any '# wbuild:' lines), or 0.
char* libref_module_summary(list[char*] lines):
	int i = 0
	while ((i < lines.length) && libref_starts(lines[i], c"# wbuild:")): i = i + 1
	if (i >= lines.length): return 0
	char* t = libref_trim(lines[i])
	int is_hash = t[0] == '#'
	int is_block = libref_starts(t, c"/*")
	free(t)
	int last = i
	if (is_hash):
		while ((last + 1 < lines.length) && (lines[last + 1][0] == '#')): last = last + 1
	else if (is_block):
		while ((last < lines.length) && (index_of(lines[last], c"*/") < 0)): last = last + 1
		if (last >= lines.length): return 0
	else:
		return 0
	return libref_paragraph(lines, i, last)


# The declaration starting at 1-based 'line', as written: a function
# signature may continue onto later lines while its parentheses are
# open. The trailing ':' that opens the body is dropped.
char* libref_declaration(list[char*] lines, int line):
	string_builder* out = string_new()
	int depth = 0
	int i = line - 1
	while (i < lines.length):
		char* l = lines[i]
		int k = 0
		while (l[k]):
			if (l[k] == '('): depth = depth + 1
			if (l[k] == ')'): depth = depth - 1
			k = k + 1
		libref_append_words(out, l)
		i = i + 1
		if (depth <= 0): break
	char* text = libref_trim(out.data)
	string_free(out)
	int n = strlen(text)
	if ((n > 0) && (text[n - 1] == ':')): text[n - 1] = 0
	char* trimmed = libref_trim(text)
	free(text)
	return trimmed


char* libref_string_field(json_value* record, char* key):
	if (json_object_has(record, key) == 0): return c""
	json_value* v = json_object_get(record, key)
	if (v.type != json_type_string()): return c""
	return v.string_value


int libref_int_field(json_value* record, char* key):
	if (json_object_has(record, key) == 0): return 0
	json_value* v = json_object_get(record, key)
	if (v.type != json_type_int()): return 0
	return v.int_value


# "`int x`, `char* name`" for a struct record's fields, or 0.
char* libref_fields(json_value* record):
	if (json_object_has(record, c"fields") == 0): return 0
	json_value* fields = json_object_get(record, c"fields")
	if (fields.type != json_type_array()): return 0
	string_builder* out = string_new()
	int i = 0
	while (i < json_array_length(fields)):
		json_value* f = json_array_get(fields, i)
		char* name = libref_string_field(f, c"name")
		# Skip padding and other compiler-made filler fields.
		if (libref_starts(name, c"__") == 0):
			if (out.length > 0): string_append(out, c", ")
			string_append_char(out, '`')
			string_append(out, libref_string_field(f, c"type"))
			string_append_char(out, ' ')
			string_append(out, name)
			string_append_char(out, '`')
		i = i + 1
	if (out.length == 0):
		string_free(out)
		return 0
	char* text = strclone(out.data)
	string_free(out)
	return text


# Runs 'bin/wv2 [arch] symbols --json path'; the result, or 0 when the
# spawn failed.
process_result* libref_symbols(char* arch, char* path):
	char** argv = strv_new(5)
	int n = 0
	strv_set(argv, n, c"bin/wv2")
	n = n + 1
	if (arch != 0):
		strv_set(argv, n, arch)
		n = n + 1
	strv_set(argv, n, c"symbols")
	strv_set(argv, n + 1, c"--json")
	strv_set(argv, n + 2, path)
	process_result* r = process_run(c"bin/wv2", argv, 0, 0, 300000)
	free(cast(char*, argv))
	return r


int libref_has_line(list[libref_decl*] decls, int line):
	for libref_decl* d in decls:
		if (d.line == line): return 1
	return 0


# Insert d into decls keeping source order.
void libref_insert(list[libref_decl*] decls, libref_decl* d):
	decls.push(d)
	int j = decls.length - 2
	while ((j >= 0) && (decls[j].line > d.line)):
		decls[j + 1] = decls[j]
		j = j - 1
	decls[j + 1] = d


# The identifier that ends just before s[at], or an empty string.
char* libref_name_before(char* s, int at):
	int start = at
	while (start > 0):
		int c = s[start - 1]
		int ident = ((c >= 'a') && (c <= 'z')) || ((c >= 'A') && (c <= 'Z')) || ((c >= '0') && (c <= '9')) || (c == '_')
		if (ident == 0): break
		start = start - 1
	return substring(s, start, at)


# 'symbols' only reports generic functions and structs that the module
# instantiates itself, so a generic library such as structures/heap.w
# would list nothing. Add every top-level generic declaration line
# ('T name[T](...):', 'struct name[T]:') that is not listed yet.
void libref_add_generic_templates(list[libref_decl*] decls, list[char*] lines):
	int i = 0
	int in_comment = 0
	while (i < lines.length):
		char* l = lines[i]
		# Lines inside a /* ... */ block are prose, not declarations.
		int open_at = index_of(l, c"/*")
		if (in_comment):
			if (index_of(l, c"*/") >= 0): in_comment = 0
			i = i + 1
			continue
		if (open_at >= 0):
			if (index_of(l + open_at, c"*/") < 0): in_comment = 1
			i = i + 1
			continue
		int c = l[0]
		int top = ((c >= 'a') && (c <= 'z')) || ((c >= 'A') && (c <= 'Z'))
		int bracket = index_of(l, c"[")
		int paren = index_of(l, c"](")
		int is_fn = top && (paren > 0)
		if (is_fn):
			# The '[' that opens the type parameters, not one in the
			# return type ('list[T] name[T](...)').
			bracket = paren
			while ((bracket > 0) && (l[bracket] != '[')): bracket = bracket - 1
		int is_struct = top && (bracket > 0) && (libref_starts(l, c"struct ") || libref_starts(l, c"union "))
		char* t = libref_trim(l)
		int opens_block = ends_with(t, c":")
		free(t)
		if ((is_fn || is_struct) && opens_block && (libref_has_line(decls, i + 1) == 0)):
			char* name = libref_name_before(l, bracket)
			if ((name[0] != 0) && (name[0] != '_')):
				libref_decl* d = new libref_decl
				d.line = i + 1
				d.group = 0
				if (is_struct): d.group = 1
				d.text = libref_declaration(lines, i + 1)
				d.doc = libref_doc_above(lines, i + 1)
				d.extra = 0
				libref_insert(decls, d)
			free(name)
		i = i + 1


int libref_is_type_kind(char* kind):
	if ((strcmp(kind, c"struct") == 0) || (strcmp(kind, c"union") == 0)): return 1
	if ((strcmp(kind, c"enum") == 0) || (strcmp(kind, c"alias") == 0)): return 1
	return strcmp(kind, c"fn") == 0


# Parse the NDJSON 'text' and keep path's own public declarations.
list[libref_decl*] libref_collect(char* path, char* text, list[char*] lines):
	list[libref_decl*] decls = new list[libref_decl*]
	char* suffix = strjoin(c"/", path)
	# Type names declared here, so the duplicate 'object' record each
	# struct also gets is not listed as a global.
	set[char*] type_names = new set[char*]
	int round = 0
	while (round < 2):
		int start = 0
		while (text[start]):
			int end = start
			while ((text[end] != 0) && (text[end] != 10)): end = end + 1
			char* row = substring(text, start, end)
			if (text[end] == 10): end = end + 1
			start = end
			if (row[0] != '{'):
				free(row)
				continue
			json_value* record = json_parse(row)
			free(row)
			if (record == 0): continue
			char* file = libref_string_field(record, c"file")
			char* name = libref_string_field(record, c"name")
			char* kind = libref_string_field(record, c"kind")
			int line = libref_int_field(record, c"line")
			int keep = ends_with(file, suffix) && (line > 0) && (line <= lines.length)
			if (keep && (name[0] == '_')): keep = 0
			int is_type = libref_is_type_kind(kind)
			if (keep && (round == 0)):
				if (is_type): type_names.add(strclone(name))
			else if (keep && (libref_has_line(decls, line) == 0)):
				int group = 2
				if (strcmp(kind, c"function") == 0): group = 0
				if (is_type): group = 1
				int skip = 0
				if ((group == 2) && (name in type_names)): skip = 1
				if (skip == 0):
					libref_decl* d = new libref_decl
					d.line = line
					d.group = group
					d.text = libref_declaration(lines, line)
					d.doc = libref_doc_above(lines, line)
					d.extra = 0
					# A generic instantiation's fields are the
					# instantiated types; the template line says more.
					if ((group == 1) && (index_of(name, c"$") < 0)): d.extra = libref_fields(record)
					libref_insert(decls, d)
			json_free(record)
		round = round + 1
	free(suffix)
	libref_add_generic_templates(decls, lines)
	return decls


void libref_emit_group(string_builder* out, list[libref_decl*] decls, int group, char* title):
	int any = 0
	for libref_decl* d in decls:
		if (d.group != group): continue
		if (any == 0):
			string_append(out, title)
			string_append(out, c"\n\n")
			any = 1
		string_append(out, c"- `")
		string_append(out, d.text)
		string_append_char(out, '`')
		if (d.extra != 0):
			string_append(out, c". Fields: ")
			string_append(out, d.extra)
			string_append_char(out, '.')
		if (d.doc != 0):
			string_append(out, c"\n  ")
			string_append(out, d.doc)
		string_append_char(out, 10)
	if (any): string_append_char(out, 10)


# "lib/vmm/box.w" -> "lib.vmm.box"
char* libref_import_name(char* path):
	char* name = substring(path, 0, strlen(path) - 2)
	int i = 0
	while (name[i]):
		if (name[i] == '/'): name[i] = '.'
		i = i + 1
	return name


void libref_module(string_builder* out, char* path):
	list[char*] lines = file_read_lines(path)
	if (lines == 0):
		println2(strjoin(c"libref: cannot read ", path))
		exit(2)
	char* arch_note = 0
	process_result* r = libref_symbols(0, path)
	if ((r != 0) && (r.status != 0)):
		process_result_free(r)
		r = libref_symbols(c"x64", path)
		arch_note = c" Compiles only for 64-bit targets; listed from the x64 build."
	string_append(out, c"## ")
	string_append(out, path)
	string_append(out, c"\n\n`import ")
	char* import_name = libref_import_name(path)
	string_append(out, import_name)
	free(import_name)
	string_append(out, c"`")
	char* summary = libref_module_summary(lines)
	if (summary != 0):
		string_append(out, c": ")
		string_append(out, summary)
		free(summary)
	if ((r != 0) && (r.status == 0) && (arch_note != 0)): string_append(out, arch_note)
	string_append(out, c"\n\n")
	if ((r == 0) || (r.status != 0)):
		string_append(out, c"Not listed: the module does not compile on its own ")
		string_append(out, c"(it is a fragment that another module imports).\n\n")
	else:
		list[libref_decl*] decls = libref_collect(path, r.stdout_text, lines)
		libref_emit_group(out, decls, 0, c"Functions:")
		libref_emit_group(out, decls, 1, c"Types:")
		libref_emit_group(out, decls, 2, c"Constants and globals:")
	if (r != 0): process_result_free(r)
	for char* l in lines: free(l)
	lines.free()


char* libref_generate():
	list[char*] paths = new list[char*]
	dir_walk_files(c"lib", paths)
	dir_walk_files(c"structures", paths)
	string_builder* out = string_new()
	string_append(out, c"# W library reference\n\n")
	string_append(out, c"Generated by `tools/libref.w` (`./wbuild library_reference`) from\n")
	string_append(out, c"`bin/wv2 symbols --json` and the source comments; it is a build product,\n")
	string_append(out, c"not a committed file. Declarations are as written in the source; struct fields\n")
	string_append(out, c"are listed for the 32-bit x86 target. Names starting with `_`, tests\n")
	string_append(out, c"and the per-target `__arch__/` modules are left out. The built-in\n")
	string_append(out, c"`map`, `set` and `list` and the prelude helpers are described in the\n")
	string_append(out, c"[README](../README.md#language-snapshot).\n\n")
	list[char*] wanted = new list[char*]
	for char* p in paths:
		if (libref_wanted(p)): wanted.push(p)
	string_append(out, c"Modules:")
	for char* p in wanted:
		string_append(out, c" [`")
		string_append(out, p)
		string_append(out, c"`](#")
		# GitHub's heading anchor: lowercased, '/' and '.' dropped.
		int i = 0
		while (p[i]):
			if ((p[i] != '/') && (p[i] != '.')): string_append_char(out, p[i])
			i = i + 1
		string_append(out, c")")
	string_append(out, c"\n\n")
	for char* p in wanted: libref_module(out, p)
	char* text = strclone(out.data)
	string_free(out)
	return text


int libref_write(char* path, char* text):
	# O_WRONLY | O_CREAT | O_TRUNC, mode rw-r--r--
	int fd = open(path, 577, 420)
	if (fd < 0): return 0
	int n = strlen(text)
	int done = 0
	while (done < n):
		int w = write(fd, text + done, n - done)
		if (w <= 0):
			close(fd)
			return 0
		done = done + w
	close(fd)
	return 1


int main(int argc, char** argv):
	if (argc != 2):
		println2(c"usage: libref <out.md>")
		return 2
	char* path = argv[1]
	char* text = libref_generate()
	if (libref_write(path, text) == 0):
		println2(strjoin(c"libref: cannot write ", path))
		return 2
	println(strjoin(c"libref: wrote ", path))
	return 0
