"""Regenerate checked-in original JPEG fixtures; reference environment: Pillow 10.2.0/libjpeg-turbo 2.1.5.

Fixtures are synthesized here, not copied from a third-party image corpus.
Tests consume the checked-in W source and require no Python or Pillow.
"""
from io import BytesIO
from pathlib import Path
from PIL import Image


def literal(data):
    return 'c"' + ''.join(f'\\x{x:02x}' for x in data) + '"'


def jpeg(image, **opts):
    out = BytesIO()
    image.save(out, format='JPEG', quality=90, **opts)
    return out.getvalue()


fixtures = []
gray = Image.new('L', (9, 9))
gray.putdata([(x * 19 + y * 5) % 256 for y in range(9) for x in range(9)])
fixtures.append(('gray', jpeg(gray), gray.size, True))
color = Image.new('RGB', (13, 9))
color.putdata([(x * 15, y * 23, (x + y) * 10) for y in range(9) for x in range(13)])
fixtures.append(('color', jpeg(color, subsampling=0), color.size, True))
for name, sampling in [('420', 2), ('422', 1)]:
    red = Image.new('RGB', (17, 17), (230, 40, 70))
    fixtures.append((name, jpeg(red, subsampling=sampling), red.size, True))
fixtures.append(('progressive', jpeg(color, progressive=True), color.size, False))
# Minimal two-MCU grayscale with restart interval 1 and zero coefficients.
def seg(marker, payload):
    return bytes([255, marker]) + (len(payload) + 2).to_bytes(2, 'big') + payload
restart = b'\xff\xd8'
restart += seg(0xdb, b'\0' + bytes([1] * 64))
restart += seg(0xc0, bytes([8, 0, 8, 0, 9, 1, 1, 0x11, 0]))
restart += seg(0xc4, bytes([0, 1] + [0] * 15 + [0, 0x10, 1] + [0] * 15 + [0]))
restart += seg(0xdd, b'\0\1')
restart += seg(0xda, bytes([1, 1, 0, 0, 63, 0]))
restart += b'\x3f\xff\xd0\x3f\xff\xd9'
fixtures.append(('restart', restart, (9, 8), True))
lines = ['# Original synthetic fixtures; generated by generate_jpeg_fixtures.py.', '']
for name, data, (width, height), golden in fixtures:
    lines += [f'const int jpeg_fixture_{name}_length = {len(data)}',
              f'char* jpeg_fixture_{name}():', '\treturn ' + literal(data), '']
    if golden:
        raw = Image.open(BytesIO(data)).convert('RGBA').tobytes()
        lines += [f'char* jpeg_golden_{name}():', '\treturn ' + literal(raw), '']
Path(__file__).with_name('jpeg_fixtures.w').write_text('\n'.join(lines))
